import { useCallback, useEffect, useRef, useState } from "react";
import { api, type Capture, type Case, type Project, type Run } from "./model";
import { CaseDetail, RunDetail } from "./evidence";
import { Campaigns, Captures, Cases, Overview, Runner } from "./views";
import { Empty, Header, Icon, Loading, Mark, Panel, RunsTable } from "./ui";
import { CommandMenu, navigation } from "./command";
export function App() {
  const [route, setRoute] = useState(location.hash.slice(1) || "overview"), [connected, setConnected] = useState(false), [sessionChecked, setSessionChecked] = useState(false), [mode, setMode] = useState("local"), [token, setToken] = useState("");
  const [projects, setProjects] = useState<Project[]>([]), [projectId, setProjectId] = useState(() => { try { return localStorage.getItem("aftershock-project") ?? ""; } catch { return ""; } }), [cases, setCases] = useState<Case[]>([]), [captures, setCaptures] = useState<Capture[]>([]), [runs, setRuns] = useState<Run[]>([]), [capabilities, setCapabilities] = useState<any>(null);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [projectName, setProjectName] = useState(""), [loaded, setLoaded] = useState(false), [dataReady, setDataReady] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false), [navOpen, setNavOpen] = useState(false);
  const [theme, setTheme] = useState<"dark" | "light">(() => document.documentElement.dataset.theme === "light" ? "light" : "dark");
  useEffect(() => { document.documentElement.dataset.theme = theme; document.querySelector("meta[name=theme-color]")?.setAttribute("content", theme === "dark" ? "#141416" : "#ffffff"); try { localStorage.setItem("aftershock-theme", theme); } catch { /* Appearance still works when browser storage is disabled. */ } }, [theme]);
  const mobileNav = useRef<HTMLDialogElement>(null);
  const shortcut = /Mac|iPhone|iPad/.test(navigator.platform) ? "⌘ K" : "Ctrl K";
  const go = useCallback((next: string) => { location.hash = next; }, []);
  useEffect(() => { const change = () => { setRoute(location.hash.slice(1) || "overview"); setNavOpen(false); window.scrollTo({ top: 0 }); requestAnimationFrame(() => document.getElementById("main")?.focus()); }; window.addEventListener("hashchange", change); return () => window.removeEventListener("hashchange", change); }, []);
  useEffect(() => { const key = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") { e.preventDefault(); setSearchOpen(value => !value); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, []);
  useEffect(() => { if (navOpen) mobileNav.current?.showModal(); else mobileNav.current?.close(); }, [navOpen]);
  useEffect(() => { const ended = () => { setConnected(false); setLoaded(false); setDataReady(false); setSearchOpen(false); }; window.addEventListener("aftershock-session-ended", ended); return () => window.removeEventListener("aftershock-session-ended", ended); }, []);
  useEffect(() => { const controller = new AbortController(); void Promise.all([api("/health", undefined, controller.signal), api("/session", undefined, controller.signal)]).then(([health, session]) => { setMode(health.mode); setConnected(session.connected); setSessionChecked(true); }).catch(e => { if (!controller.signal.aborted) { setError(e.message); setSessionChecked(true); } }); return () => controller.abort(); }, []);
  useEffect(() => {
    if (!connected) return; const controller = new AbortController();
    void Promise.all([api<Project[]>("/projects", undefined, controller.signal), api("/capabilities", undefined, controller.signal)]).then(([all, caps]) => { setProjects(all); setCapabilities(caps); setLoaded(true); if (!all.some(p => p.id === projectId)) setProjectId(all[0]?.id ?? ""); }).catch(e => { if (!controller.signal.aborted) setError(e.message); });
    return () => controller.abort();
  }, [connected]);
  useEffect(() => {
    if (!connected || !projectId) return; try { localStorage.setItem("aftershock-project", projectId); } catch { /* Project selection remains available without storage. */ }
    const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>;
    const refresh = async () => { try {
      const [allCases, allCaptures, allRuns] = await Promise.all([api<Case[]>(`/projects/${projectId}/cases`, undefined, controller.signal), api<Capture[]>(`/projects/${projectId}/captures`, undefined, controller.signal), api<Run[]>(`/projects/${projectId}/runs`, undefined, controller.signal)]);
      if (controller.signal.aborted) return; setDataReady(true); setCases(allCases); setCaptures(allCaptures); setRuns(allRuns); timer = setTimeout(refresh, allRuns.some(r => ["QUEUED", "RUNNING"].includes(r.state)) ? 2000 : 6000);
    } catch (e) { if (!controller.signal.aborted) { setError((e as Error).message); timer = setTimeout(refresh, 4000); } } };
    setDataReady(false); setCases([]); setCaptures([]); setRuns([]); void refresh(); return () => { controller.abort(); clearTimeout(timer); };
  }, [connected, projectId]);
  const submit = async (settings: Record<string, unknown>) => {
    if (busy) return; setBusy(true); setError("");
    try { const job = await api<Run>("/runs", { ...settings, projectId, idempotencyKey: crypto.randomUUID() }); setRuns(previous => [job, ...previous]); go(`run/${job.id}`); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  };
  const pair = async () => { setBusy(true); setError(""); try { await api("/session", mode === "local" ? {} : { token }); setToken(""); setConnected(true); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const create = async () => { setBusy(true); setError(""); try { const project = await api<Project>("/projects", { name: projectName, adapter: "maintained-trade-ledger-v1" }); setProjects(previous => [...previous, project]); setProjectId(project.id); setProjectName(""); go("overview"); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const project = projects.find(p => p.id === projectId), actions = { go, submit, busy }, page = route.split("/")[0];
  const activePage = page === "run" ? "campaigns" : page === "case" ? "cases" : page === "capture" ? "captures" : page;
  const pageName = page === "run" ? "Run details" : page === "case" ? "Case details" : navigation.find(n => n.id === activePage)?.name ?? "Overview";
  const incidentCount = runs.filter(r => r.kind === "campaign" && r.verdict === "FAIL").length;
  const sidebarContent = <>
    <a className="brand" href="#overview" aria-label="Aftershock overview"><Mark /><span>Aftershock</span></a>
    <div className="project-picker"><div className="project-avatar"><Icon name="box" /></div><label><span className="sr-only">Project</span><select value={projectId} onChange={e => { setProjectId(e.target.value); go("overview"); setNavOpen(false); }} disabled={!connected || !projects.length}><option value="" disabled>Select project</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>
    <button className="workspace-search" onClick={() => { setNavOpen(false); setSearchOpen(true); }}><Icon name="search" /><span>Search</span><kbd>{shortcut}</kbd></button>
    <span className="nav-label">Workspace</span><nav aria-label="Workbench">{navigation.slice(0, 5).map(n => <a key={n.id} href={`#${n.id}`} onClick={() => setNavOpen(false)} aria-current={activePage === n.id ? "page" : undefined} className={activePage === n.id ? "selected" : ""}><Icon name={n.id} /><span>{n.name}</span>{n.id === "incidents" && incidentCount > 0 && <span className="nav-count">{incidentCount}</span>}</a>)}</nav>
    <details className="new-project"><summary><Icon name="plus" />New project</summary><form onSubmit={e => { e.preventDefault(); void create(); }}><label><span className="sr-only">Project name</span><input placeholder="Project name" maxLength={80} value={projectName} onChange={e => setProjectName(e.target.value)} required /></label><button disabled={!connected || busy}>Create project</button></form></details>
    <div className="sidebar-bottom"><a href="#runner" onClick={() => setNavOpen(false)} aria-current={page === "runner" ? "page" : undefined} className={page === "runner" ? "selected" : ""}><Icon name="settings" />Runner settings</a><a href="https://github.com/hicksonhaziel/Aftershock" target="_blank" rel="noreferrer"><Icon name="source" />Source code<Icon name="external" /></a><div className="runner-state"><div className="runner-icon"><Icon name="runner" /></div><div><strong>{connected ? mode === "local" ? "Local runner" : "Hosted samples" : "Disconnected"}</strong><span>{connected ? "Session connected" : "Connection required"}</span></div><span className={connected ? "connected-dot" : "offline-dot"} /></div></div>
  </>;
  return <div className="app"><a className="skip" href="#main" onClick={e => { e.preventDefault(); document.getElementById("main")?.focus(); }}>Skip to content</a><aside className="sidebar desktop-sidebar">{sidebarContent}</aside><dialog ref={mobileNav} className="mobile-nav" aria-label="Navigation" onCancel={() => setNavOpen(false)} onClick={e => { if (e.target === e.currentTarget) setNavOpen(false); }}><aside className="sidebar"><button className="icon-button nav-close" aria-label="Close navigation" onClick={() => setNavOpen(false)}><Icon name="close" /></button>{sidebarContent}</aside></dialog>
    <CommandMenu open={searchOpen} close={() => setSearchOpen(false)} go={go} cases={connected ? cases : []} runs={connected ? runs : []} captures={connected ? captures : []} />
    <div className="workspace"><header className="topbar"><div className="breadcrumbs"><button className="icon-button mobile-toggle" aria-label="Open navigation" onClick={() => setNavOpen(true)}><Icon name="menu" /></button><Icon name="folder" /><span className="project-crumb">{project?.name ?? "Workspace"}</span><span className="crumb-divider">/</span><strong>{pageName}</strong></div><div className="topbar-actions"><div className="theme-switch" role="group" aria-label="Color mode"><button aria-label="Dark mode" aria-pressed={theme === "dark"} onClick={() => setTheme("dark")} title="Dark mode"><Icon name="moon" /><span>Dark</span></button><button aria-label="White mode" aria-pressed={theme === "light"} onClick={() => setTheme("light")} title="White mode"><Icon name="sun" /><span>White</span></button></div><span className="environment"><span className={connected ? "connected-dot" : "offline-dot"} />{mode === "local" ? "Local" : "Hosted samples"}</span><button className="icon-button" aria-label="Search workspace" title="Search workspace (Ctrl/⌘ K)" onClick={() => setSearchOpen(true)}><Icon name="search" /></button></div></header><main id="main" tabIndex={-1}>{error && <div className="alert" role="alert"><Icon name="incidents" /><span>{error}</span><button className="icon-button" onClick={() => setError("")} aria-label="Dismiss error"><Icon name="close" /></button></div>}<div className="page-content" key={route}>
      {!sessionChecked ? <Loading text="Checking connection…" /> : !connected ? <div className="connect"><div className="connection-art" aria-hidden="true"><div className="connection-grid" /><div className="connection-emblem"><Mark /></div><span className="connection-caption">AFTERSHOCK</span></div><div className="connect-content"><span className="eyebrow">Solana regression workbench</span><h1>Connect your runner.</h1><p>Record inputs, test recovery, and save the failure as an offline test.</p><div className="connect-box"><h2>{mode === "local" ? "Local workspace" : "Maintained sample workspace"}</h2><p>{mode === "local" ? "Recordings and execution stay on this machine." : "Enter the access token from your operator."}</p><form onSubmit={e => { e.preventDefault(); void pair(); }}>{mode !== "local" && <label>Access token<input type="password" autoComplete="off" value={token} onChange={e => setToken(e.target.value)} required /></label>}<button className="primary" disabled={busy}>{busy ? "Connecting…" : "Connect runner"}<Icon name="arrow" /></button></form></div><span className="connection-foot"><Icon name="box" />Maintained trade ledger · Isolated PostgreSQL</span></div></div>
      : !loaded ? <Loading text="Loading projects…" /> : !project ? <Empty title="Create your first project" text="Name your project to start testing the maintained trade sample."><form className="form" onSubmit={e => { e.preventDefault(); void create(); }}><label>Project name<input value={projectName} maxLength={80} onChange={e => setProjectName(e.target.value)} required /></label><button className="primary" disabled={busy}>Create project</button></form></Empty>
      : !dataReady ? <Loading text="Loading project…" />
      : page === "run" && route.split("/")[1] ? <RunDetail key={route} id={route.split("/")[1]!} runs={runs} {...actions} />
      : page === "case" && route.split("/")[1] ? <CaseDetail key={route} id={route.split("/")[1]!} initialInput={route.split("/")[2]} {...actions} />
      : page === "captures" || page === "capture" ? <Captures key={project.id} initialCapture={route.split("/")[1]} captures={captures} runs={runs} {...actions} />
      : page === "campaigns" ? <Campaigns key={`${project.id}-${cases.length === 0}-${route}`} initialCase={route.split("/")[1]} cases={cases} runs={runs} {...actions} />
      : page === "cases" ? <Cases cases={cases} runs={runs} go={go} />
      : page === "incidents" ? <><Header title="Incidents" description="Failed assertions from the maintained trade sample." /><Panel title="Assertion failures"><RunsTable searchable runs={runs.filter(r => r.kind === "campaign" && r.verdict === "FAIL")} go={go} emptyTitle="No failed assertions" emptyText="Campaigns with a FAIL verdict will appear here." /></Panel></>
      : page === "runner" ? <Runner capabilities={capabilities} mode={mode} />
      : <Overview project={project} cases={cases} captures={captures} runs={runs} go={go} />}
    </div><footer className="main-footer"><span><Mark />Aftershock</span><span>Maintained trade sample</span><button className="text-button" onClick={() => go("runner")}>Runner settings <Icon name="external" /></button></footer></main></div></div>;
}
