import { useEffect, useRef, useState } from "react";
import { scenarioName, short, type Capture, type Case, type Run } from "./model";
import { Icon, operationName } from "./ui";
export const navigation = [{ id: "overview", name: "Overview" }, { id: "captures", name: "Captures" }, { id: "campaigns", name: "Campaigns" }, { id: "incidents", name: "Incidents" }, { id: "cases", name: "Case library" }, { id: "runner", name: "Runner settings" }];
export function CommandMenu({ open, close, go, cases, runs, captures }: { open: boolean; close: () => void; go: (route: string) => void; cases: Case[]; runs: Run[]; captures: Capture[] }) {
  const dialog = useRef<HTMLDialogElement>(null), input = useRef<HTMLInputElement>(null);
  const [query, setQuery] = useState(""), [selected, setSelected] = useState(0);
  useEffect(() => { if (open) { setQuery(""); setSelected(0); dialog.current?.showModal(); input.current?.focus(); } else dialog.current?.close(); }, [open]);
  const options = [...navigation.map(n => ({ route: n.id, title: n.name, detail: "Page", icon: n.id })), ...runs.map(r => ({ route: `run/${r.id}`, title: `${operationName(r.kind)} · ${short(r.id)}`, detail: r.verdict ?? r.state, icon: "campaigns" })), ...cases.map(c => ({ route: `case/${c.id}`, title: `Case ${short(c.id)}`, detail: scenarioName(c), icon: "cases" })), ...captures.map(c => ({ route: `capture/${c.summary.captureId}`, title: `Capture ${short(c.summary.captureId)}`, detail: `${c.summary.transactions} transactions`, icon: "captures" }))].filter(o => `${o.title} ${o.detail} ${o.route}`.toLowerCase().includes(query.toLowerCase())).slice(0, 12);
  const index = Math.min(selected, Math.max(0, options.length - 1));
  useEffect(() => { document.getElementById(`command-option-${index}`)?.scrollIntoView({ block: "nearest" }); }, [index, query]);
  const choose = (route: string) => { close(); go(route); };
  return <dialog ref={dialog} className="command-dialog" aria-label="Search workspace" onCancel={close} onClick={e => { if (e.target === e.currentTarget) close(); }}><div className="command-surface"><div className="command-input"><Icon name="search" /><input ref={input} aria-label="Search pages, runs, cases and captures" placeholder="Search pages, runs, cases and captures…" value={query} role="combobox" aria-expanded="true" aria-controls="command-results" aria-activedescendant={options.length ? `command-option-${index}` : undefined} autoComplete="off" onChange={e => { setQuery(e.target.value); setSelected(0); }} onKeyDown={e => { if (e.key === "ArrowDown" || e.key === "ArrowUp") { e.preventDefault(); setSelected((index + (e.key === "ArrowDown" ? 1 : -1) + options.length) % Math.max(1, options.length)); } if (e.key === "Enter" && options[index]) { e.preventDefault(); choose(options[index].route); } }} /><button className="icon-button" aria-label="Close search" onClick={close}><Icon name="close" /></button></div><div className="command-results" id="command-results" role="listbox" aria-label="Results">{options.map((o, i) => <div key={o.route} id={`command-option-${i}`} role="option" aria-selected={index === i} className={index === i ? "active" : ""} onMouseMove={() => setSelected(i)} onClick={() => choose(o.route)}><Icon name={o.icon} /><span>{o.title}</span><small>{o.detail}</small><Icon name="arrow" /></div>)}{!options.length && <p className="command-empty">No results for “{query}”</p>}</div><div className="command-footer"><span><kbd>↑</kbd><kbd>↓</kbd> Navigate</span><span><kbd>↵</kbd> Open</span><span><kbd>esc</kbd> Close</span></div></div></dialog>;
}
