import { useEffect, useState } from "react";
import { api, base, bytes, short, stamp, type Run } from "./model";
import { Header, JsonView, Panel, Status } from "./ui";
import type { Actions } from "./views";
function delta(value: string) { try { return BigInt(value).toLocaleString(); } catch { return value; } }
function Provenance({ value, go }: { value: any; go: Actions["go"] }) {
  if (!value) return null;
  return <Panel title="Source & coverage" caption="THE INPUTS THIS RESULT ACTUALLY USED"><dl className="facts"><dt>Source</dt><dd><span className="label">{value.sourceMode}</span></dd><dt>Parent capture</dt><dd className="mono hash">{value.capture?.captureId ?? "Synthetic fixture · no chain capture"}</dd><dt>Manifest SHA-256</dt><dd className="mono hash">{value.capture?.manifest?.sha256 ?? "—"}</dd><dt>Slot interval</dt><dd className="mono">{value.coverage?.startSlot ?? "—"} → {value.coverage?.endSlot ?? "—"}</dd><dt>Coverage</dt><dd>{value.coverage?.status ?? "not assessed"}</dd><dt>Finalized reference</dt><dd>{value.reference?.result?.verdict ?? "Not attached"}</dd><dt>Explicit exclusions</dt><dd>{value.coverage?.exclusions?.length ?? 0}</dd></dl><p className="muted">{value.coverage?.scope}</p>{value.capture?.captureId && <button className="text-button" onClick={() => go(`capture/${value.capture.captureId}`)}>Inspect the source recording ↗</button>}{value.reference && <details><summary>Inspect finalized membership & boundary evidence</summary><JsonView value={value.reference} /></details>}{value.coverage?.exclusions?.length > 0 && <details><summary>Show excluded inputs</summary><JsonView value={value.coverage.exclusions} /></details>}</Panel>;
}
function Discrepancies({ rows }: { rows: any[] }) {
  return <div className="table-wrap"><table className="discrepancy-table"><thead><tr><th>Assertion field</th><th>Expected</th><th>Observed</th><th>Difference</th></tr></thead><tbody>{rows.map((d, i) => <tr key={i}><td><strong>{d.field === "count" ? "Trade contributions" : d.field === "solLamports" ? "SOL · lamports" : d.field === "tokenBaseUnits" ? "Token · base units" : d.field ?? d.kind}</strong><span className="muted row-detail">{d.kind}</span></td><td className="mono">{delta(d.expected ?? "—")}</td><td className="mono">{delta(d.actual ?? "—")}</td><td className="mono difference">{d.delta ? `${BigInt(d.delta) > 0 ? "+" : ""}${delta(d.delta)}` : "Changed"}</td></tr>)}</tbody></table></div>;
}
export function RunDetail({ id, go, submit, busy, runs }: { id: string; runs: Run[] } & Actions) {
  const [job, setJob] = useState<Run | null>(null), [events, setEvents] = useState<any[]>([]), [evidence, setEvidence] = useState<Record<string, any>>({}), [error, setError] = useState(""), [connected, setConnected] = useState(true);
  useEffect(() => {
    const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>, cursor = 0, stream: EventSource | undefined;
    setJob(null); setEvents([]); setEvidence({}); setError("");
    const refresh = async () => { try {
      const value = await api(`/runs/${id}/events?after=${cursor}`, undefined, controller.signal);
      setJob(value.job); setEvents(previous => [...new Map([...previous, ...value.events].map(e => [e.sequence, e])).values()].sort((a, b) => a.sequence - b.sequence)); cursor = Math.max(cursor, value.nextCursor); setConnected(true);
      if (!["COMPLETED", "CANCELLED"].includes(value.job.state) && !stream) {
        stream = new EventSource(`${base}/runs/${id}/stream?after=${cursor}`);
        stream.addEventListener("progress", event => { const e = JSON.parse((event as MessageEvent).data); cursor = Math.max(cursor, e.sequence); setEvents(previous => [...new Map([...previous, e].map(item => [item.sequence, item])).values()].sort((a, b) => a.sequence - b.sequence)); setConnected(true); });
        stream.onerror = () => setConnected(false);
      }
      if (["COMPLETED", "CANCELLED"].includes(value.job.state)) stream?.close();
      if (!["COMPLETED", "CANCELLED"].includes(value.job.state)) timer = setTimeout(refresh, 1500);
    } catch (e) { if (!controller.signal.aborted) { setError((e as Error).message); setConnected(false); timer = setTimeout(refresh, 3000); } } };
    void refresh(); return () => { controller.abort(); clearTimeout(timer); stream?.close(); };
  }, [id]);
  useEffect(() => {
    if (!job?.result?.artifacts?.length) return;
    const controller = new AbortController();
    const refs = job.result.artifacts.filter((r: any) => ["faulted/recovery-trace.json", "faulted/state.json", "input.json"].includes(r.name));
    void Promise.all(refs.map(async (r: any) => [r.name, await api(`/runs/${id}/artifacts/${r.id}`, undefined, controller.signal)] as const)).then(entries => setEvidence(Object.fromEntries(entries))).catch(e => { if (!controller.signal.aborted) setError((e as Error).message); });
    return () => controller.abort();
  }, [id, job?.result?.artifacts]);
  if (!job) return <><Header eyebrow="SAVED RUN" title="Loading the evidence…" /><p role="status">{error || "Connecting to this run’s durable progress."}</p></>;
  const result = job.result, active = ["RUNNING", "QUEUED"].includes(job.state), crash = evidence["faulted/recovery-trace.json"]?.find((e: any) => e.kind === "crash"), state = evidence["faulted/state.json"], input = evidence["input.json"], fault = result?.faulted;
  const confirmedId = result?.caseId, linkedId = confirmedId ?? job.caseId;
  const derivedIds = new Set([linkedId]);
  for (let step = 0; step < runs.length; step++) for (const r of runs) if (r.caseId && derivedIds.has(r.caseId) && ["reduce", "compare"].includes(r.kind) && r.result?.caseId) derivedIds.add(r.result.caseId);
  const related = runs.filter(r => r.caseId && derivedIds.has(r.caseId) && ["reduce", "compare", "export"].includes(r.kind));
  const verifiedComparison = related.find(r => r.kind === "compare" && r.verdict === "PASS")?.result?.comparison;
  const title = job.kind === "campaign" ? job.verdict === "FAIL" ? "Inspect the failed assertion." : "Inspect the campaign result." : job.kind === "reduce" ? "Keep the failure. Remove the noise." : job.kind === "compare" ? "Does the fix survive the same fault?" : job.kind === "export" ? "An offline test, ready to keep." : `${job.kind[0]?.toUpperCase()}${job.kind.slice(1)} operation`;
  return <><Header eyebrow={`${job.kind.toUpperCase()} / ${short(id)}`} title={title} description={`${stamp(job.createdAtUtc)} · Attempt ${job.attempt} · ${job.maxSeconds}s execution budget`}><Status value={job.verdict ?? job.state} />{active && <button disabled={job.cancelRequested || busy} onClick={async () => { try { setJob(await api(`/runs/${id}/cancel`, {})); } catch (e) { setError((e as Error).message); } }}>{job.cancelRequested ? "Stopping & cleaning up…" : "Cancel run"}</button>}</Header>
    {error && <div role="alert" className="alert">{error} {connected ? "" : "Reconnecting to saved progress…"}</div>}
    <div className="run-bar"><span className="mono hash">Run {job.id}</span><span>{active ? "◷ Progress saved on the runner" : "✓ Saved result"}</span><span>{result?.provenance?.sourceMode ?? result?.capture?.sourceMode ?? (active ? "Awaiting evidence" : "Operation evidence saved")}</span></div>
    {job.kind === "capture" && active && <Panel title="Live recording" caption="SOLAMI MAINNET · BOUNDED ACCOUNT FILTER"><div className="lane-strip"><div><span>State</span><strong>{events.some(e => e.payload.stage === "recording") ? "Recording raw messages" : "Connecting to provider"}</strong></div><div><span>Transactions / frames</span><strong>{events.filter(e => e.payload.stage === "recording").at(-1)?.payload.transactions ?? 0} / {events.filter(e => e.payload.stage === "recording").at(-1)?.payload.frames ?? 0}</strong></div><div><span>Raw bytes</span><strong>{bytes(events.filter(e => e.payload.stage === "recording").at(-1)?.payload.rawBytes ?? 0)}</strong></div><div><span>Last received</span><strong>{events.filter(e => e.payload.stage === "recording").at(-1)?.payload.receivedAtUtc ? stamp(events.filter(e => e.payload.stage === "recording").at(-1).payload.receivedAtUtc) : "Waiting for first frame"}</strong></div></div><p className="muted">Finalization and normalization begin after sealing. Cancellation stops recording and retains local partial evidence.</p></Panel>}
    {result?.capture && <Panel title="Recording sealed" caption="RAW INTEGRITY VERIFIED · REFERENCE NOT YET ASSESSED"><dl className="facts"><dt>Capture</dt><dd className="mono hash">{result.capture.captureId}</dd><dt>Recorded</dt><dd>{stamp(result.capture.startedAtUtc)}</dd><dt>Transactions / frames</dt><dd>{result.capture.transactions} / {result.capture.frames.length}</dd><dt>Raw size</dt><dd>{bytes(result.capture.rawBytes)}</dd><dt>Stopped</dt><dd>{result.capture.stopReason}</dd></dl>{result.captureId ? <button className="text-button" onClick={() => go(`capture/${result.capture.captureId}`)}>Open recording & prepare trades ↗</button> : <details><summary>Inspect retained capture manifest</summary><JsonView value={result.capture} /></details>}</Panel>}
    {result?.reference && <Panel title="Finalized reference result" caption="MEMBERSHIP CHECK · CAPTURE COMPLETENESS SEPARATE"><dl className="facts"><dt>Verdict</dt><dd><Status value={result.reference.result.verdict} /></dd><dt>Present / absent</dt><dd>{result.reference.result.transactions.filter((r: any) => r.status === "present").length} / {result.reference.result.transactions.filter((r: any) => r.status === "absent").length}</dd><dt>Reference coverage</dt><dd>{result.reference.result.referenceCoverage}</dd><dt>Boundary matches</dt><dd>{result.reference.reconstruction?.notObservedInCapture?.length ?? "Not reconstructed"} not observed in this recording</dd><dt>Capture completeness</dt><dd>Not established</dd></dl><details><summary>Inspect full finalized reference evidence</summary><JsonView value={result.reference} /></details></Panel>}
    {job.kind === "campaign" && result && <>
      <div className="lane-strip"><div><span>01 / Clean baseline</span><Status value={result.baseline?.verdict ?? "NOT RUN"} /></div><div><span>02 / Faulted execution</span><Status value={fault?.verdict ?? "NOT RUN"} /></div><div><span>Required fault applied</span><strong>{fault ? fault.requiredFaultsApplied ? "✓ Verified" : "! Not established" : "—"}</strong></div><div><span>Unique event rows</span><strong>{state?.events?.length ?? "—"}</strong></div></div>
      {job.verdict === "FAIL" && <div className="incident-explanation"><span className="eyebrow">WHAT WENT WRONG</span><h2>{crash ? "Saved effects moved ahead of the recovery checkpoint." : "The declared expected state differs from the saved state."}</h2><p>{crash ? "The faulty sample saved the trade, then stopped before saving its checkpoint. On restart, the same input returned. The unique event row stayed deduplicated, but the sample added its contribution to the total again." : "The declared aggregate differs from the saved consumer state. Inspect the applied fault and exact fields below before drawing a cause."}</p><p className="muted">Intentional maintained sample defect · {result.provenance?.assertion?.kind ?? "trade-state assertion"}</p></div>}
      {result.discrepancies?.length > 0 && <Panel title="The assertion evidence" caption="EXACT INTEGER AMOUNTS · MINTS REMAIN SEPARATE"><Discrepancies rows={result.discrepancies} /><details><summary>Inspect group identities & full discrepancies</summary><JsonView value={result.discrepancies} /></details></Panel>}
      {crash && <Panel title="The commit / checkpoint gap" caption={`ACTUAL SUPERVISOR TRACE · ${crash.inputId}`}><div className="causal-timeline"><div><b>01</b><strong>Trade committed</strong><p>Through delivery <code>{crash.barrier.committedThrough}</code></p></div><div className="fault-step"><b>02</b><strong>Process terminated</strong><p><code>{crash.termination}</code> · exit {crash.exitObserved ? "observed" : "unverified"}</p></div><div><b>03</b><strong>Checkpoint inspected</strong><p>Last durable: <code>{crash.durableCheckpoint ?? "empty"}</code></p></div><div><b>04</b><strong>Restart & inspect</strong><p>Required fault {fault?.requiredFaultsApplied ? "applied" : "not established"}</p></div></div><p className="muted">The fixed variant saves the effects and checkpoint in the same database transaction. Finite comparisons verify this behavior on the recorded case.</p><button className="text-button" onClick={() => go(`case/${linkedId}`)}>Inspect anchored source {crash.inputId} ↗</button><details><summary>Show the full recovery trace</summary><JsonView value={evidence["faulted/recovery-trace.json"]} /></details></Panel>}
      {input && <Panel title="Recorded business events" caption="A TRANSACTION CAN CONTAIN MORE THAN ONE EVENT"><div className="table-wrap"><table><thead><tr><th>Input</th><th>Signature</th><th>Slot</th><th>Business events</th><th>Delivery role</th></tr></thead><tbody>{input.deliveries.map((d: any) => <tr key={d.inputId}><td><button className="text-button mono" onClick={() => go(`case/${linkedId}`)}>{d.inputId} ↗</button></td><td className="mono" title={d.signature}>{short(d.signature)}…</td><td className="mono">{d.slot}</td><td>{d.events.length}</td><td>{d.inputId === crash?.inputId ? <span className="label anchor">FAULT ANCHOR</span> : "Recorded input"}</td></tr>)}</tbody></table></div></Panel>}
      {confirmedId && <div className="action-band"><div><strong>Keep a regression for this failure.</strong><p>A confirmed case is saved. Reduce it, then verify the fix against the same failure.</p><p>After downloading its export, reproduce with <code>node regression.mjs reproduce . faulty</code> and test the fix with <code>node regression.mjs test . fixed</code>.</p></div><button className="primary" disabled={busy} onClick={() => void submit({ kind: "reduce", caseId: confirmedId, maxAttempts: 10, maxSeconds: 600 })}>Reduce this failure <span aria-hidden="true">→</span></button><button onClick={() => go(`case/${confirmedId}`)}>Open confirmed case</button></div>}
    </>}
    {job.kind === "campaign" && verifiedComparison && <Comparison report={verifiedComparison} />}
    {result?.reduction && <Reduction proof={result.reduction} />}
    {result?.comparison && <Comparison report={result.comparison} />}
    {result?.download && <Panel title="Verified regression bundle" caption="NO PROVIDER KEYS REQUIRED AFTER CAPTURE"><dl className="facts"><dt>Archive</dt><dd>{result.download.name}</dd><dt>Size</dt><dd>{bytes(result.download.bytes)}</dd><dt>SHA-256</dt><dd className="mono hash">{result.download.sha256}</dd></dl><a className="button primary" href={`${base}/runs/${id}/download`} download>Download offline case ↓</a><p className="muted">Requires Linux, the exact bundled Node version, local Docker and the cached pinned PostgreSQL image. See the included README.</p><JsonView value={result.commands} /></Panel>}
    {result?.explanation && <div className="note">{result.explanation}</div>}
    {result?.caseId && job.kind !== "campaign" && <div className="action-band"><div><strong>Case {short(result.caseId)} is saved.</strong><p>Carry the same input and failure identity into the next step.</p></div><button className="primary" onClick={() => go(`case/${result.caseId}`)}>Open saved case →</button></div>}
    <Provenance value={result?.provenance} go={go} />
    <Panel title="Durable progress" caption={connected ? "CONNECTED · RESUMES AFTER REFRESH" : "RECONNECTING"}><ol className="progress-list" aria-live="polite">{events.map(e => <li key={e.sequence}><span className="mono">{String(e.sequence).padStart(2, "0")}</span><p>{e.payload.message}</p><time>{stamp(e.createdAtUtc)}</time></li>)}</ol></Panel>
    {result?.artifacts?.length > 0 && <Panel title="Evidence files" caption="CHECKSUMMED · SERVER-SELECTED ARTIFACTS"><div className="artifact-list">{result.artifacts.map((a: any) => <a key={a.id} href={`${base}/runs/${id}/artifacts/${a.id}`} target="_blank" rel="noreferrer"><span className="mono">{a.name}</span><span>{bytes(a.bytes)} ↗</span></a>)}</div></Panel>}
    {related.length > 0 && <Panel title="Next-step results">{related.map(r => <p key={r.id}><button className="text-button" onClick={() => go(`run/${r.id}`)}>{r.kind} · {short(r.id)} ↗</button> <Status value={r.verdict ?? r.state} /></p>)}</Panel>}
  </>;
}
export function Reduction({ proof }: { proof: any }) { return <Panel title="Reduction result" caption="SAME FAILURE IDENTITY · ORIGINAL PRESERVED"><div className="reduction-hero"><div><span>Original inputs</span><strong>{proof.originalInputs}</strong></div><span aria-hidden="true">→</span><div><span>Retained inputs</span><strong>{proof.retainedInputs.length}</strong></div><div className="reduction-bytes"><span>Raw payload</span><strong>{bytes(proof.originalRawBytes)} → {bytes(proof.retainedRawBytes)}</strong></div></div><dl className="facts"><dt>Failure fingerprint</dt><dd className="mono hash">{proof.failureFingerprint}</dd><dt>Reduction claim</dt><dd>{proof.minimality}</dd><dt>Measured attempts</dt><dd>{proof.attempts.length} / {proof.budget.maxAttempts}</dd><dt>Original retained</dt><dd>{proof.originalPreserved ? "Yes" : "Not verified"}</dd></dl><div className="two-col inset"><div><h3>Retained prerequisites & anchors</h3>{proof.preserved.prerequisites.map((r: any, i: number) => <p key={i}><code>{r.inputId}</code> — {r.reason}</p>)}<p className="muted">Initial state, supporting evidence and stable fault configuration are preserved.</p></div><div><h3>Removed inputs</h3><p className="mono wrap">{proof.removedInputs.join(" · ") || "None"}</p></div></div><details><summary>Inspect candidates & reproduction history</summary><JsonView value={proof} /></details></Panel>; }
export function Comparison({ report }: { report: any }) { return <Panel title="Pinned faulty / fixed comparison" caption="FINITE FRESH-STATE RUNS · SAME INPUT & FAULT"><p className="muted">{report.meaning}</p>{report.cases.map((c: any) => <div key={c.caseId}><div className="comparison-grid"><div className="faulty-result"><span>Intentional faulty variant</span><strong>{c.faultyConfirmed} / {c.repeats}</strong><p>Recorded failure reproduced</p></div><div className="fixed-result"><span>Fixed variant</span><strong>{c.fixedPassed} / {c.repeats}</strong><p>Assertion passed with required fault applied</p></div></div><div className="table-wrap"><table><thead><tr><th>Attempt</th><th>Variant</th><th>Assertion</th><th>Fault applied</th><th>Reset / cleanup</th></tr></thead><tbody>{c.attempts.map((a: any, i: number) => <tr key={a.runId ?? i}><td className="mono">{short(a.runId)}</td><td>{a.variant}</td><td><Status value={a.verdict} /></td><td>{a.requiredFaultsApplied ? "✓ Verified" : "! Missing"}</td><td>{a.resetVerified ? "Fresh state" : "Unverified"} / {a.cleanup}</td></tr>)}</tbody></table></div></div>)}</Panel>; }
export function CaseDetail({ id, go, submit, busy }: { id: string } & Actions) {
  const [detail, setDetail] = useState<any>(null), [source, setSource] = useState<any>(null), [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); setDetail(null); setSource(null); setError(""); void api(`/cases/${id}`, undefined, controller.signal).then(setDetail).catch(e => { if (!controller.signal.aborted) setError(e.message); }); return () => controller.abort(); }, [id]);
  if (!detail) return <p role="status">{error || "Loading immutable case…"}</p>;
  const confirmed = !!detail.spec.failureFingerprint;
  return <><Header eyebrow={`CASE / ${short(id)}`} title={confirmed ? "A failure worth keeping." : "Recorded inputs. Declared expectations."} description={`${detail.input.deliveries.length} transaction input${detail.input.deliveries.length === 1 ? "" : "s"} · ${detail.provenance.events} business event${detail.provenance.events === 1 ? "" : "s"}`} />
    {error && <div role="alert" className="alert">{error}</div>}
    <div className="action-band"><div><strong>{confirmed ? "Confirmed failure identity" : "Ready for a campaign"}</strong><p>{confirmed ? "Reduction, comparisons and exports use this locked case." : "Run the faulty variant to establish an inspectable failure."}</p></div>{confirmed ? <><button className="primary" disabled={busy} onClick={() => void submit({ kind: "compare", caseId: id, repeats: 5, maxSeconds: 1200 })}>Verify fix · 5 pairs</button><button disabled={busy} onClick={() => void submit({ kind: "export", caseId: id, maxSeconds: 120 })}>Prepare offline export ↓</button></> : <button className="primary" disabled={busy} onClick={() => void submit({ kind: "campaign", caseId: id, variant: "faulty", maxSeconds: 360 })}>Run faulty campaign →</button>}</div>
    <Provenance value={detail.provenance} go={go} />
    <Panel title="Source drill-down" caption="RAW BYTES · SIGNATURE · INSTRUCTION PATH · BUSINESS EVENT IDENTITY"><div className="table-wrap"><table><thead><tr><th>Input</th><th>Signature</th><th>Slot</th><th>Events</th></tr></thead><tbody>{detail.input.deliveries.map((d: any) => <tr key={d.inputId}><td><button className="text-button mono" onClick={async () => { try { setSource(await api(`/cases/${id}/sources/${encodeURIComponent(d.inputId)}`)); } catch (e) { setError((e as Error).message); } }}>{d.inputId} ↗</button></td><td className="mono" title={d.signature}>{short(d.signature)}…</td><td className="mono">{d.slot}</td><td>{d.events.length}</td></tr>)}</tbody></table></div>{source && <div className="source-detail"><h3>Source {source.inputId}</h3><dl className="facts"><dt>Transaction signature</dt><dd className="mono hash">{source.signature}</dd><dt>Raw SHA-256</dt><dd className="mono hash">{source.sha256}</dd><dt>Payload</dt><dd>{bytes(source.bytes)} · {detail.input.source === "synthetic" ? "synthetic fixture bytes" : "original protobuf"}</dd></dl><details open><summary>Decoded business events & exact amounts</summary><JsonView value={source.events} /></details><details><summary>Raw source payload (base64)</summary><pre className="json wrap">{source.payload}</pre></details></div>}</Panel>
    {detail.reduction && <Reduction proof={detail.reduction} />}
    <Panel title="Case contract"><dl className="facts"><dt>Failure fingerprint</dt><dd className="mono hash">{detail.spec.failureFingerprint ?? "Not yet established"}</dd><dt>Assertion</dt><dd>{detail.spec.assertion?.kind ?? "Expected trade state"}</dd></dl><details><summary>Inspect scenario, expectations & reproduction history</summary><JsonView value={{ scenario: detail.spec.scenario, expectedFailure: detail.spec.expectedFailure, expected: detail.expected, history: detail.history }} /></details></Panel>
  </>;
}
