import { useEffect, useRef, useState } from "react";
import { api, base, bytes, short, stamp, type Run } from "./model";
import { CopyButton, Header, Icon, JsonView, Loading, Panel, Status, Tabs } from "./ui";
import { relatedCaseRuns, sourceName } from "./workflow";
import type { Actions } from "./views";
function delta(value: string) { try { return BigInt(value).toLocaleString(); } catch { return value; } }
function Provenance({ value, go }: { value: any; go: Actions["go"] }) {
  if (!value) return null;
  return <Panel title="Source & coverage" caption="Recorded inputs and exclusions"><dl className="facts"><dt>Source</dt><dd><span className="label">{sourceName(value.sourceMode)}</span></dd><dt>Parent capture</dt><dd className="mono hash">{value.capture?.captureId ?? "Synthetic fixture · no chain capture"}</dd><dt>Manifest SHA-256</dt><dd className="mono hash">{value.capture?.manifest?.sha256 ?? "—"}</dd><dt>Slot interval</dt><dd className="mono">{value.coverage?.startSlot ?? "—"} → {value.coverage?.endSlot ?? "—"}</dd><dt>Coverage</dt><dd>{value.coverage?.status ?? "not assessed"}</dd><dt>Finalized reference</dt><dd>{value.reference?.result?.verdict ?? "Not attached"}</dd><dt>Explicit exclusions</dt><dd>{value.coverage?.exclusions?.length ?? 0}</dd></dl><p className="muted">{value.coverage?.scope}</p>{value.capture?.captureId && <button className="text-button" onClick={() => go(`capture/${value.capture.captureId}`)}>Inspect the source recording <Icon name="external" /></button>}{value.reference && <details><summary>Inspect finalized membership & boundary evidence</summary><JsonView value={value.reference} /></details>}{value.coverage?.exclusions?.length > 0 && <details><summary>Show excluded inputs</summary><JsonView value={value.coverage.exclusions} /></details>}</Panel>;
}
function Discrepancies({ rows }: { rows: any[] }) {
  return <div className="table-wrap"><table className="discrepancy-table"><thead><tr><th>Assertion field</th><th>Expected</th><th>Observed</th><th>Difference</th></tr></thead><tbody>{rows.map((d, i) => <tr key={i}><td><strong>{d.field === "count" ? "Trade contributions" : d.field === "solLamports" ? "SOL · lamports" : d.field === "tokenBaseUnits" ? "Token · base units" : d.field ?? d.kind}</strong><span className="muted row-detail">{d.kind}</span></td><td className="mono">{delta(d.expected ?? "—")}</td><td className="mono">{delta(d.actual ?? "—")}</td><td className="mono difference">{d.delta ? `${BigInt(d.delta) > 0 ? "+" : ""}${delta(d.delta)}` : "Changed"}</td></tr>)}</tbody></table></div>;
}
export function RunDetail({ id, go, submit, busy, runs }: { id: string; runs: Run[] } & Actions) {
  const [tab, setTab] = useState("summary");
  const [job, setJob] = useState<Run | null>(null), [events, setEvents] = useState<any[]>([]), [evidence, setEvidence] = useState<Record<string, any>>({}), [error, setError] = useState(""), [connected, setConnected] = useState(true);
  useEffect(() => {
    const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>, cursor = 0, stream: EventSource | undefined;
    setJob(null); setEvents([]); setEvidence({}); setError("");
    const refresh = async () => { try {
      const value = await api(`/runs/${id}/events?after=${cursor}`, undefined, controller.signal);
      setJob(value.job); setEvents(previous => [...new Map([...previous, ...value.events].map(e => [e.sequence, e])).values()].sort((a, b) => a.sequence - b.sequence)); cursor = Math.max(cursor, value.nextCursor); setConnected(true);
      if (!["COMPLETED", "CANCELLED"].includes(value.job.state) && !stream) {
        stream = new EventSource(`${base}/runs/${id}/stream?after=${cursor}`);
        stream.addEventListener("progress", event => { const e = JSON.parse((event as MessageEvent).data); cursor = Math.max(cursor, e.sequence); setEvents(previous => [...new Map([...previous, e].map(item => [item.sequence, item])).values()].sort((a, b) => a.sequence - b.sequence)); setConnected(true); });
        stream.onerror = () => setConnected(false);
      }
      if (["COMPLETED", "CANCELLED"].includes(value.job.state)) stream?.close();
      if (!["COMPLETED", "CANCELLED"].includes(value.job.state)) timer = setTimeout(refresh, 1500);
    } catch (e) { if (!controller.signal.aborted) { setError((e as Error).message); setConnected(false); timer = setTimeout(refresh, 3000); } } };
    void refresh(); return () => { controller.abort(); clearTimeout(timer); stream?.close(); };
  }, [id]);
  useEffect(() => {
    if (!job?.result?.artifacts?.length) return;
    const controller = new AbortController();
    const refs = job.result.artifacts.filter((r: any) => ["faulted/recovery-trace.json", "faulted/state.json", "input.json"].includes(r.name));
    void Promise.all(refs.map(async (r: any) => [r.name, await api(`/runs/${id}/artifacts/${r.id}`, undefined, controller.signal)] as const)).then(entries => setEvidence(Object.fromEntries(entries))).catch(e => { if (!controller.signal.aborted) setError((e as Error).message); });
    return () => controller.abort();
  }, [id, job?.result?.artifacts]);
  if (!job) return <>{error ? <div className="alert" role="alert">{error}</div> : <Loading text="Loading run…" />}</>;
  const result = job.result, active = ["RUNNING", "QUEUED"].includes(job.state), crash = evidence["faulted/recovery-trace.json"]?.find((e: any) => e.kind === "crash"), state = evidence["faulted/state.json"], input = evidence["input.json"], fault = result?.faulted;
  const confirmedId = result?.caseId, linkedId = confirmedId ?? job.caseId;
  const related = relatedCaseRuns(runs, linkedId);
  const verifiedRun = related.find(r => r.kind === "compare" && r.verdict === "PASS"), verifiedComparison = verifiedRun?.result?.comparison;
  const title = job.kind === "campaign" ? job.verdict === "FAIL" ? "Failed assertion" : "Campaign result" : job.kind === "reduce" ? "Case reduction" : job.kind === "compare" ? "Fix comparison" : job.kind === "export" ? "Offline export" : `${job.kind[0]?.toUpperCase()}${job.kind.slice(1)} operation`;
  return <><button className="back-link text-button" onClick={() => go(job.kind === "campaign" ? "campaigns" : ["capture", "reference", "normalize"].includes(job.kind) ? "captures" : "cases")}><Icon name="back" />Back to {job.kind === "campaign" ? "campaigns" : ["capture", "reference", "normalize"].includes(job.kind) ? "captures" : "cases"}</button><Header eyebrow={`${job.kind} / ${short(id)}`} title={title} description={`${stamp(job.createdAtUtc)} · Attempt ${job.attempt} · ${job.maxSeconds}s execution budget`}><Status value={job.verdict ?? job.state} />{active && <button disabled={job.cancelRequested || busy} onClick={async () => { try { setJob(await api(`/runs/${id}/cancel`, {})); } catch (e) { setError((e as Error).message); } }}>{job.cancelRequested ? "Stopping & cleaning up…" : "Cancel run"}</button>}</Header>
    {error && <div role="alert" className="alert">{error} {connected ? "" : "Reconnecting to saved progress…"}</div>}
    <div className="run-bar"><span className="run-id"><span className="mono hash">{job.id}</span><CopyButton value={job.id} /></span><span><Icon name={active ? "clock" : "check"} />{active ? "Progress saved" : "Saved result"}</span><span>{sourceName(result?.provenance?.sourceMode ?? result?.capture?.sourceMode)}</span></div>
    <Tabs id="run-view" value={tab} choose={setTab} options={[{ id: "summary", label: "Summary" }, { id: "source", label: "Source & files" }, { id: "log", label: "Run log" }]} />
    <div role="tabpanel" id="run-view-summary-panel" aria-labelledby="run-view-summary-tab" hidden={tab !== "summary"}>
    {job.kind === "capture" && active && <Panel title="Live recording" caption="SOLAMI MAINNET · BOUNDED ACCOUNT FILTER"><div className="lane-strip"><div><span>State</span><strong>{events.some(e => e.payload.stage === "recording") ? "Recording raw messages" : "Connecting to provider"}</strong></div><div><span>Transactions / frames</span><strong>{events.filter(e => e.payload.stage === "recording").at(-1)?.payload.transactions ?? 0} / {events.filter(e => e.payload.stage === "recording").at(-1)?.payload.frames ?? 0}</strong></div><div><span>Raw bytes</span><strong>{bytes(events.filter(e => e.payload.stage === "recording").at(-1)?.payload.rawBytes ?? 0)}</strong></div><div><span>Last received</span><strong>{events.filter(e => e.payload.stage === "recording").at(-1)?.payload.receivedAtUtc ? stamp(events.filter(e => e.payload.stage === "recording").at(-1).payload.receivedAtUtc) : "Waiting for first frame"}</strong></div></div><p className="muted">Finalization and normalization begin after sealing. Cancellation stops recording and retains local partial evidence.</p></Panel>}
    {result?.capture && <Panel title="Recording sealed" caption="RAW INTEGRITY VERIFIED · REFERENCE NOT YET ASSESSED"><dl className="facts"><dt>Capture</dt><dd className="mono hash">{result.capture.captureId}</dd><dt>Recorded</dt><dd>{stamp(result.capture.startedAtUtc)}</dd><dt>Transactions / frames</dt><dd>{result.capture.transactions} / {result.capture.frames.length}</dd><dt>Raw size</dt><dd>{bytes(result.capture.rawBytes)}</dd><dt>Stopped</dt><dd>{result.capture.stopReason}</dd></dl>{result.captureId ? <button className="text-button" onClick={() => go(`capture/${result.capture.captureId}`)}>Open recording & prepare trades <Icon name="external" /></button> : <details><summary>Inspect retained capture manifest</summary><JsonView value={result.capture} /></details>}</Panel>}
    {result?.reference && <Panel title="Finalized reference result" caption="MEMBERSHIP CHECK · CAPTURE COMPLETENESS SEPARATE"><dl className="facts"><dt>Verdict</dt><dd><Status value={result.reference.result.verdict} /></dd><dt>Present / absent</dt><dd>{result.reference.result.transactions.filter((r: any) => r.status === "present").length} / {result.reference.result.transactions.filter((r: any) => r.status === "absent").length}</dd><dt>Reference coverage</dt><dd>{result.reference.result.referenceCoverage}</dd><dt>Boundary matches</dt><dd>{result.reference.reconstruction?.notObservedInCapture?.length ?? "Not reconstructed"} not observed in this recording</dd><dt>Capture completeness</dt><dd>Not established</dd></dl><details><summary>Inspect full finalized reference evidence</summary><JsonView value={result.reference} /></details></Panel>}
    {job.kind === "campaign" && result && <>
      <div className="lane-strip"><div><span>01 / Clean baseline</span><Status value={result.baseline?.verdict ?? "NOT RUN"} /></div><div><span>02 / Faulted execution</span><Status value={fault?.verdict ?? "NOT RUN"} /></div><div><span>Required fault applied</span><strong>{fault ? fault.requiredFaultsApplied ? "✓ Verified" : "! Not established" : "—"}</strong></div><div><span>Unique event rows</span><strong>{state?.events?.length ?? "—"}</strong></div></div>
      {job.verdict === "FAIL" && <div className="incident-explanation"><span className="eyebrow">WHAT WENT WRONG</span><h2>{crash ? "The trade was counted twice after restart." : "Saved state differs from the expected state."}</h2><p>{crash ? "The trade committed before the checkpoint. After the crash, replay kept the event row unique but added its contribution to the total again." : "The fields below show the difference. Check the applied fault and source inputs to trace the cause."}</p><p className="muted">Intentional maintained sample defect · {result.provenance?.assertion?.kind ?? "trade-state assertion"}</p></div>}
      {result.discrepancies?.length > 0 && <Panel title="Discrepancies" caption="Integer amounts, grouped by mint"><Discrepancies rows={result.discrepancies} /><details><summary>Inspect group identities & full discrepancies</summary><JsonView value={result.discrepancies} /></details></Panel>}
      {crash && <Panel title="Commit & recovery" caption={`ACTUAL SUPERVISOR TRACE · ${crash.inputId}`}><div className="causal-timeline"><div><b>01</b><strong>Trade committed</strong><p>Through delivery <code>{crash.barrier.committedThrough}</code></p></div><div className="fault-step"><b>02</b><strong>Process terminated</strong><p><code>{crash.termination}</code> · exit {crash.exitObserved ? "observed" : "unverified"}</p></div><div><b>03</b><strong>Checkpoint inspected</strong><p>Last durable: <code>{crash.durableCheckpoint ?? "empty"}</code></p></div><div><b>04</b><strong>Restart & inspect</strong><p>Required fault {fault?.requiredFaultsApplied ? "applied" : "not established"}</p></div></div><p className="muted">The fixed variant saves the effects and checkpoint in the same database transaction. Finite comparisons verify this behavior on the recorded case.</p><button className="text-button" onClick={() => go(`case/${linkedId}/${crash.inputId}`)}>Inspect anchored source {crash.inputId} <Icon name="external" /></button><details><summary>Show the full recovery trace</summary><JsonView value={evidence["faulted/recovery-trace.json"]} /></details></Panel>}

      {confirmedId && <div className="action-band"><div><strong>Save this failure as a regression.</strong><p>Reduce the saved case, then compare the faulty and fixed variants.</p><p>Download the export for the offline commands and locked inputs.</p></div><button className="primary" disabled={busy} onClick={() => void submit({ kind: "reduce", caseId: confirmedId, maxAttempts: 10, maxSeconds: 600 })}>Reduce this failure <Icon name="arrow" /></button><button onClick={() => go(`case/${confirmedId}`)}>Open confirmed case</button></div>}
    </>}
    {job.kind === "campaign" && !active && verifiedComparison && <Panel title="Saved fix comparison" caption={`Earlier result · ${stamp(verifiedRun!.createdAtUtc)}`} action={<button className="text-button" onClick={() => go(`run/${verifiedRun!.id}`)}>Open comparison <Icon name="arrow" /></button>}><p className="muted">Faulty: {verifiedComparison.cases[0].faultyConfirmed}/{verifiedComparison.cases[0].repeats} reproduced · Fixed: {verifiedComparison.cases[0].fixedPassed}/{verifiedComparison.cases[0].repeats} passed</p></Panel>}
    {result?.reduction && <Reduction proof={result.reduction} />}
    {result?.comparison && <Comparison report={result.comparison} />}
    {result?.download && <Panel title="Verified regression bundle" caption="NO PROVIDER KEYS REQUIRED AFTER CAPTURE"><dl className="facts"><dt>Archive</dt><dd>{result.download.name}</dd><dt>Size</dt><dd>{bytes(result.download.bytes)}</dd><dt>SHA-256</dt><dd className="mono hash">{result.download.sha256}</dd></dl><a className="button primary" href={`${base}/runs/${id}/download`} download>Download offline case <Icon name="download" /></a><p className="muted">Requires Linux, the exact bundled Node version, local Docker and the cached pinned PostgreSQL image. See the included README.</p><JsonView value={result.commands} /></Panel>}
    {result?.explanation && <div className="note">{result.explanation}</div>}
    {result?.caseId && job.kind !== "campaign" && <div className="action-band"><div><strong>Case {short(result.caseId)} is saved.</strong><p>Open the case to run a comparison or prepare an export.</p></div><button className="primary" onClick={() => go(`case/${result.caseId}`)}>Open saved case <Icon name="arrow" /></button></div>}
    {active && <div className="active-progress" role="status"><span className="status running"><Icon name="clock" />{job.state}</span><span>{events.at(-1)?.payload.message ?? "Waiting for a worker…"}</span><button className="text-button" onClick={() => setTab("log")}>View log <Icon name="arrow" /></button></div>}
    </div>
    <div role="tabpanel" id="run-view-source-panel" aria-labelledby="run-view-source-tab" hidden={tab !== "source"}>
      {input && <Panel title="Recorded business events" caption="A TRANSACTION CAN CONTAIN MORE THAN ONE EVENT"><div className="table-wrap"><table><thead><tr><th>Input</th><th>Signature</th><th>Slot</th><th>Business events</th><th>Delivery role</th></tr></thead><tbody>{input.deliveries.map((d: any) => <tr key={d.inputId}><td><button className="text-button mono" onClick={() => go(`case/${linkedId}/${d.inputId}`)}>{d.inputId} <Icon name="external" /></button></td><td className="mono" title={d.signature}>{short(d.signature)}…</td><td className="mono">{d.slot}</td><td>{d.events.length}</td><td>{d.inputId === crash?.inputId ? <span className="label anchor">FAULT ANCHOR</span> : "Recorded input"}</td></tr>)}</tbody></table></div></Panel>}
    <Provenance value={result?.provenance} go={go} />
    {result?.artifacts?.length > 0 && <Panel title="Evidence files" caption="Checksummed artifacts"><div className="artifact-list">{result.artifacts.map((a: any) => <a key={a.id} href={`${base}/runs/${id}/artifacts/${a.id}`} target="_blank" rel="noreferrer"><span className="mono">{a.name}</span><span>{bytes(a.bytes)} ↗</span></a>)}</div></Panel>}
    {!result && <Panel title="Source & files"><p className="muted">Evidence appears as the run completes.</p></Panel>}
    </div>
    <div role="tabpanel" id="run-view-log-panel" aria-labelledby="run-view-log-tab" hidden={tab !== "log"}>
    <Panel title="Run log" caption={connected ? "Saved progress" : "Reconnecting…"}><ol className="progress-list" aria-live="polite">{events.map(e => <li key={e.sequence}><span className="mono">{String(e.sequence).padStart(2, "0")}</span><p>{e.payload.message}</p><time>{stamp(e.createdAtUtc)}</time></li>)}</ol></Panel>

    {related.length > 0 && <Panel title="Related runs">{related.map(r => <p key={r.id}><button className="text-button" onClick={() => go(`run/${r.id}`)}>{r.kind} · {short(r.id)} <Icon name="external" /></button> <Status value={r.verdict ?? r.state} /></p>)}</Panel>}
    </div>
  </>;
}
export function Reduction({ proof }: { proof: any }) { return <Panel title="Reduction result" caption="Original case preserved"><div className="reduction-hero"><div><span>Original inputs</span><strong>{proof.originalInputs}</strong></div><span aria-hidden="true">→</span><div><span>Retained inputs</span><strong>{proof.retainedInputs.length}</strong></div><div className="reduction-bytes"><span>Raw payload</span><strong>{bytes(proof.originalRawBytes)} → {bytes(proof.retainedRawBytes)}</strong></div></div><dl className="facts"><dt>Failure fingerprint</dt><dd className="mono hash">{proof.failureFingerprint}</dd><dt>Reduction claim</dt><dd>{proof.minimality === "1-minimal-under-declared-transaction-units" ? "1-minimal under transaction units" : proof.minimality}</dd><dt>Measured attempts</dt><dd>{proof.attempts.length} / {proof.budget.maxAttempts}</dd><dt>Original retained</dt><dd>{proof.originalPreserved ? "Yes" : "Not verified"}</dd></dl><div className="two-col inset"><div><h3>Retained prerequisites & anchors</h3>{proof.preserved.prerequisites.map((r: any, i: number) => <p key={i}><code>{r.inputId}</code> — {r.reason}</p>)}<p className="muted">Initial state, supporting evidence and stable fault configuration are preserved.</p></div><div><h3>Removed inputs</h3><p className="mono wrap">{proof.removedInputs.join(" · ") || "None"}</p></div></div><details><summary>Inspect candidates & reproduction history</summary><JsonView value={proof} /></details></Panel>; }
export function Comparison({ report }: { report: any }) { return <Panel title="Pinned faulty / fixed comparison" caption="Same inputs and faults, fresh state for each attempt"><p className="muted">{report.meaning}</p>{report.cases.map((c: any) => <div key={c.caseId}><div className="comparison-grid"><div className="faulty-result"><span>Intentional faulty variant</span><strong>{c.faultyConfirmed} / {c.repeats}</strong><p>Recorded failure reproduced</p></div><div className="fixed-result"><span>Fixed variant</span><strong>{c.fixedPassed} / {c.repeats}</strong><p>Assertion passed with required fault applied</p></div></div><div className="table-wrap"><table><thead><tr><th>Attempt</th><th>Variant</th><th>Assertion</th><th>Fault applied</th><th>Reset / cleanup</th></tr></thead><tbody>{c.attempts.map((a: any, i: number) => <tr key={a.runId ?? i}><td className="mono">{short(a.runId)}</td><td>{a.variant}</td><td><Status value={a.verdict} /></td><td>{a.requiredFaultsApplied ? "✓ Verified" : "! Missing"}</td><td>{a.resetVerified ? "Fresh state" : "Unverified"} / {a.cleanup}</td></tr>)}</tbody></table></div></div>)}</Panel>; }
export function CaseDetail({ id, go, submit, busy, initialInput }: { id: string; initialInput?: string } & Actions) {
  const [detail, setDetail] = useState<any>(null), [sourceId, setSourceId] = useState(initialInput ?? ""), [error, setError] = useState("");
  const sourceButtons = useRef(new Map<string, HTMLButtonElement>());
  useEffect(() => { const controller = new AbortController(); setDetail(null); setSourceId(initialInput ?? ""); setError(""); void api(`/cases/${id}`, undefined, controller.signal).then(setDetail).catch(e => { if (!controller.signal.aborted) setError(e.message); }); return () => controller.abort(); }, [id, initialInput]);
  if (!detail) return <>{error ? <div className="alert" role="alert">{error}</div> : <Loading text="Loading case…" />}</>;
  const confirmed = !!detail.spec.failureFingerprint;
  return <><button className="back-link text-button" onClick={() => go("cases")}><Icon name="back" />Case library</button><Header eyebrow={`CASE / ${short(id)}`} title={confirmed ? "Regression case" : "Source case"} description={`${detail.input.deliveries.length} transaction input${detail.input.deliveries.length === 1 ? "" : "s"} · ${detail.provenance.events} business event${detail.provenance.events === 1 ? "" : "s"}`}><button onClick={() => go(`campaigns/${id}`)}><Icon name="campaigns" />Run campaign</button></Header>
    {error && <div role="alert" className="alert">{error}</div>}
    <div className="action-band"><div><strong>{confirmed ? "Confirmed failure identity" : "Ready for a campaign"}</strong><p>{confirmed ? "Reduction, comparisons and exports use this locked case." : "Run the faulty variant to establish an inspectable failure."}</p></div>{confirmed ? <><button className="primary" disabled={busy} onClick={() => void submit({ kind: "compare", caseId: id, repeats: 5, maxSeconds: 1200 })}>Verify fix · 5 pairs</button><button disabled={busy} onClick={() => void submit({ kind: "export", caseId: id, maxSeconds: 120 })}>Prepare offline export <Icon name="download" /></button></> : <button className="primary" disabled={busy} onClick={() => void submit({ kind: "campaign", caseId: id, variant: "faulty", maxSeconds: 360 })}>Run faulty campaign <Icon name="arrow" /></button>}</div>
    <Provenance value={detail.provenance} go={go} />
    <Panel title="Source drill-down" caption="Raw inputs and decoded business events"><div className="table-wrap"><table><thead><tr><th>Input</th><th>Signature</th><th>Slot</th><th>Events</th></tr></thead><tbody>{detail.input.deliveries.map((d: any) => <tr key={d.inputId}><td><button className="text-button mono" ref={button => { if (button) sourceButtons.current.set(d.inputId, button); else sourceButtons.current.delete(d.inputId); }} aria-pressed={sourceId === d.inputId} onClick={() => setSourceId(d.inputId)}>{d.inputId} <Icon name="external" /></button></td><td className="mono" title={d.signature}>{short(d.signature)}…</td><td className="mono">{d.slot}</td><td>{d.events.length}</td></tr>)}</tbody></table></div>{sourceId && <SourceInspector caseId={id} inputId={sourceId} synthetic={detail.input.source === "synthetic"} close={() => { sourceButtons.current.get(sourceId)?.focus(); setSourceId(""); }} />}</Panel>
    {detail.reduction && <Reduction proof={detail.reduction} />}
    <Panel title="Case contract"><dl className="facts"><dt>Failure fingerprint</dt><dd className="mono hash">{detail.spec.failureFingerprint ?? "Not yet established"}</dd><dt>Assertion</dt><dd>{detail.spec.assertion?.kind ?? "Expected trade state"}</dd></dl><details><summary>Inspect scenario, expectations & reproduction history</summary><JsonView value={{ scenario: detail.spec.scenario, expectedFailure: detail.spec.expectedFailure, expected: detail.expected, history: detail.history }} /></details></Panel>
  </>;
}

function SourceInspector({ caseId, inputId, synthetic, close }: { caseId: string; inputId: string; synthetic: boolean; close: () => void }) {
  const [source, setSource] = useState<any>(null), [error, setError] = useState("");
  const panel = useRef<HTMLElement>(null);
  useEffect(() => {
    const controller = new AbortController();
    setSource(null); setError("");
    panel.current?.focus({ preventScroll: true });
    panel.current?.scrollIntoView({ behavior: matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth", block: "nearest" });
    void api(`/cases/${caseId}/sources/${encodeURIComponent(inputId)}`, undefined, controller.signal).then(value => { if (!controller.signal.aborted) setSource(value); }).catch(e => { if (!controller.signal.aborted) setError(e.message); });
    return () => controller.abort();
  }, [caseId, inputId]);
  return <section ref={panel} className="source-detail" tabIndex={-1} onKeyDown={e => { if (e.key === "Escape") close(); }} aria-label={`Source ${inputId}`}><div className="source-detail-head"><h3>Source <span className="mono">{inputId}</span></h3><button className="icon-button" aria-label="Close source inspector" onClick={close}><Icon name="close" /></button></div>{error ? <div className="alert" role="alert">{error}</div> : !source ? <Loading text="Reading source…" /> : <><dl className="facts"><dt>Signature</dt><dd className="mono hash">{source.signature}<CopyButton value={source.signature} label="Copy signature" /></dd><dt>Raw SHA-256</dt><dd className="mono hash">{source.sha256}<CopyButton value={source.sha256} label="Copy raw hash" /></dd><dt>Payload</dt><dd>{bytes(source.bytes)} · {synthetic ? "Synthetic fixture bytes" : "Original protobuf"}</dd></dl><div className="decoded-events"><h3>Decoded events</h3>{source.events.map((event: any, index: number) => <article className="event-card" key={index}><div className="event-card-head"><span className="label">{event.side}</span><span>Instruction <span className="mono">{event.identity.instructionPath.join(".")}</span></span><span>Event <span className="mono">{event.identity.ordinal}</span></span></div><dl className="facts"><dt>Mint</dt><dd className="mono hash">{event.mint}<CopyButton value={event.mint} label="Copy mint" /></dd><dt>Slot</dt><dd className="mono">{event.slot}</dd></dl><div className="event-amounts"><div><span>SOL · lamports</span><strong className="mono">{delta(event.solLamports)}</strong></div><div><span>Token · base units</span><strong className="mono">{delta(event.tokenBaseUnits)}</strong></div></div></article>)}</div><details><summary>Full event records</summary><JsonView value={source.events} /></details><details><summary>Raw payload (base64)</summary><pre className="json wrap">{source.payload}</pre></details></>}</section>;
}
