import { useEffect, useState, type FormEvent } from "react";
import { api, bytes, presets, scenarioName, short, stamp, type Capture, type Case, type Project, type Run } from "./model";
import { Empty, Header, Icon, JsonView, Panel, RunsTable, Status } from "./ui";
export type Actions = { go: (route: string) => void; submit: (settings: Record<string, unknown>) => Promise<void>; busy: boolean };
export function Overview({ project, cases, captures, runs, go }: { project: Project; cases: Case[]; captures: Capture[]; runs: Run[] } & Pick<Actions, "go">) {
  const failure = runs.find(r => r.kind === "campaign" && r.verdict === "FAIL"), active = runs.filter(r => ["QUEUED", "RUNNING"].includes(r.state));
  return <><Header eyebrow="PROJECT OVERVIEW" title="Make the failure explain itself." description="Record the inputs. Break the consumer. Keep the evidence." ><button className="primary" onClick={() => go("captures")}>New capture <Icon name="arrow" /></button></Header>
    <div className="workflow" aria-label="Capture to fix workflow">{[{ n: "01", title: "Record", route: "captures", text: `${captures.length} recordings` }, { n: "02", title: "Challenge", route: "campaigns", text: `${runs.filter(r => r.kind === "campaign").length} campaigns` }, { n: "03", title: "Explain", route: "incidents", text: `${runs.filter(r => r.kind === "campaign" && r.verdict === "FAIL").length} incidents` }, { n: "04", title: "Keep", route: "cases", text: `${cases.length} cases` }].map(s => <button key={s.n} onClick={() => go(s.route)}><span className="step-number">{s.n}</span><strong>{s.title}</strong><span>{s.text}</span><Icon name="arrow" /></button>)}</div>
    <div className="overview-grid"><Panel title={failure ? "A trade survived. Its total did not." : "Your next investigation starts here."} caption={failure ? "LATEST ASSERTION FAILURE · MAINTAINED SAMPLE" : "MAINTAINED TRADE LEDGER"} className="spotlight" action={failure && <Status value="FAIL" />}>
      <p className="spotlight-text">{failure ? "The consumer kept unique trade rows, but added a contribution again during recovery. Inspect the exact difference, then turn it into a smaller regression test." : "Aftershock compares the saved consumer state with declared trade expectations. Choose a recording or an existing case to begin."}</p>
      {failure && <div className="delta-preview">{failure.result?.discrepancies?.slice(0, 3).map((d: any) => <div key={d.field}><span>{d.field === "count" ? "Extra trade contributions" : d.field === "solLamports" ? "Extra lamports" : "Extra token base units"}</span><strong className="mono">+{d.delta}</strong></div>)}</div>}
      <button className="text-button" onClick={() => go(failure ? `run/${failure.id}` : "campaigns")}>{failure ? "Open the investigation" : "Configure a campaign"} <Icon name="arrow" /></button></Panel>
      <Panel title="Execution boundary" caption={project.name}><dl className="facts"><dt>Consumer</dt><dd>Maintained trade ledger</dd><dt>State</dt><dd>Disposable PostgreSQL</dd><dt>Active jobs</dt><dd>{active.length} / 2 worker leases</dd><dt>Input coverage</dt><dd>Declared per recording</dd></dl><div className="note">An intentional sample bug. Verdicts describe these saved inputs and applied faults.</div><button className="text-button" onClick={() => go("runner")}>Inspect capabilities ↗</button></Panel></div>
    <Panel title="Recent work" caption="Durable IDs. Saved progress. Inspectable results." action={<button className="text-button" onClick={() => go("campaigns")}>All campaigns ↗</button>}><RunsTable runs={runs.slice(0, 7)} go={go} /></Panel></>;
}
export function Captures({ captures, runs, submit, go, busy, initialCapture }: { captures: Capture[]; runs: Run[]; initialCapture?: string } & Actions) {
  const [duration, setDuration] = useState(10), [transactions, setTransactions] = useState(25), [commitment, setCommitment] = useState("confirmed"), [selected, setSelected] = useState<string | null>(null), [exclude, setExclude] = useState(false);
  useEffect(() => { if (initialCapture) setSelected(captures.find(c => c.summary.captureId === initialCapture)?.id ?? null); }, [initialCapture, captures]);
  const current = captures.find(c => c.id === selected);
  const launch = (e: FormEvent) => { e.preventDefault(); void submit({ kind: "capture", durationSeconds: duration, maxTransactions: transactions, maxBytes: 2097152, commitment, maxSeconds: 120 }); };
  return <><Header eyebrow="01 / RECORD" title="Capture a bounded slice of mainnet." description="Raw messages are saved before decoding. Recording and finalization are separate." />
    <div className="two-col"><Panel title="New live capture" caption="SOLAMI · YELLOWSTONE · SOLANA MAINNET"><form onSubmit={launch} className="form"><div className="source-line"><span className="source-dot" /> Pump.fun account mention filter</div><p className="muted">Successful, non-vote transactions mentioning the program. This filter alone does not establish a program invocation or a decoded swap.</p><div className="form-row"><label>Duration (seconds)<input type="number" min="1" max="30" value={duration} onChange={e => setDuration(+e.target.value)} required /></label><label>Transaction cap<input type="number" min="1" max="100" value={transactions} onChange={e => setTransactions(+e.target.value)} required /></label></div><label>Commitment<select value={commitment} onChange={e => setCommitment(e.target.value)}><option value="confirmed">Confirmed</option><option value="finalized">Finalized</option></select></label><div className="note">Stops at the first limit: time, transactions, 200 frames or 2 MB. Uses the runner’s configured provider access.</div><button className="primary" disabled={busy}>Start live capture <Icon name="captures" /></button></form></Panel>
      <Panel title="Recording → reference → trades" caption="THREE DIFFERENT CLAIMS"><ol className="explain-list"><li><strong>Record & seal</strong><p>Keep the original bytes and their hashes. Show when recording started and why it stopped.</p></li><li><strong>Check finalized membership</strong><p>Ask the reference source which recorded transactions appear in finalized blocks. Partial boundary blocks remain explicit.</p></li><li><strong>Decode supported trades</strong><p>Use the pinned decoder. v1 inputs require explicit exclusion; they cannot silently become tested events.</p></li></ol></Panel></div>
    <Panel title="Recordings on this runner" caption="Timestamps belong to the recording itself, including saved replays.">
      {!captures.length ? <Empty title="No registered recordings" text="Start a bounded live capture, or import an existing recording with the local CLI." /> : <div className="table-wrap"><table><thead><tr><th>Capture</th><th>Source</th><th>Recorded</th><th>Transactions</th><th>Size</th><th>Reference</th></tr></thead><tbody>{captures.map(c => <tr key={c.id}><td><button className="text-button mono" onClick={() => setSelected(c.id)}>{short(c.summary.captureId)} ↗</button></td><td><span className="label">{c.summary.sourceMode === "live-mainnet" ? "LIVE RECORDING" : "SAVED MAINNET"}</span></td><td>{stamp(c.summary.startedAtUtc)}</td><td>{c.summary.transactions}</td><td>{bytes(c.summary.rawBytes)}</td><td><Status value={c.reference?.result?.verdict ?? "NOT ASSESSED"} /></td></tr>)}</tbody></table></div>}
    </Panel>
    {current && <Panel title={`Recording ${short(current.summary.captureId)}`} caption="SEALED RAW EVIDENCE" action={<button className="text-button" onClick={() => setSelected(null)}>Close detail ×</button>}><div className="two-col inset"><div><dl className="facts"><dt>Stopped</dt><dd>{current.summary.stopReason}</dd><dt>Manifest SHA-256</dt><dd className="mono hash">{current.manifestSha256}</dd><dt>Last received</dt><dd>{current.summary.frames?.at(-1)?.receivedAtUtc ?? "See frame manifest"}</dd><dt>Completeness</dt><dd>Not established</dd></dl><button disabled={busy} onClick={() => void submit({ kind: "reference", captureId: current.id, maxSeconds: 180 })}>Check finalized reference</button>{current.reference && <details><summary>Inspect finalized reference</summary><JsonView value={current.reference} /></details>}</div><form className="form" onSubmit={e => { e.preventDefault(); void submit({ kind: "normalize", captureId: current.id, allowV1Exclusions: exclude, preset: "crash", seed: "workbench", maxSeconds: 180 }); }}><h3>Prepare a trade case</h3><p className="muted">Normalization keeps the actual capture ID, source signatures, raw hashes and exclusions.</p><label className="check"><input type="checkbox" checked={exclude} onChange={e => setExclude(e.target.checked)} /> Explicitly exclude unsupported v1 inputs</label><button className="primary" disabled={busy}>Decode & prepare case <Icon name="arrow" /></button></form></div><details><summary>Inspect capture manifest</summary><JsonView value={current.summary} /></details></Panel>}
    <Panel title="Capture operations"><RunsTable runs={runs.filter(r => ["capture", "normalize", "reference"].includes(r.kind))} go={go} /></Panel></>;
}
export function Campaigns({ cases, runs, submit, go, busy }: { cases: Case[]; runs: Run[] } & Actions) {
  const [selected, setSelected] = useState(cases[0]?.id ?? ""), [preset, setPreset] = useState("crash"), [seed, setSeed] = useState("workbench"), [variant, setVariant] = useState("faulty");
  const current = cases.find(c => c.id === selected), choice = presets.find(p => p.id === preset)!;
  return <><Header eyebrow="02 / CHALLENGE" title="One input set. A controlled failure." description="Every campaign checks a clean baseline before applying the selected case’s fault." />
    <div className="two-col"><Panel title="Configure the case" caption="STABLE INPUTS · SEEDED FAULT ANCHOR"><form className="form" onSubmit={e => { e.preventDefault(); void submit({ kind: "scenario", caseId: selected, preset, seed }); }}><label>Source case<select value={selected} onChange={e => setSelected(e.target.value)} required><option value="" disabled>Select a case</option>{cases.map(c => <option key={c.id} value={c.id}>{short(c.id)} · {c.provenance.inputs} input{c.provenance.inputs === 1 ? "" : "s"} · {c.provenance.sourceMode}</option>)}</select></label><label>Fault preset<select value={preset} onChange={e => setPreset(e.target.value)}>{presets.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Seed<input maxLength={80} value={seed} onChange={e => setSeed(e.target.value)} required /></label><div className="note"><strong>{choice.name}</strong><p>{choice.text}</p><p>{choice.expectation}</p></div><button disabled={busy || !selected}>Save scenario as a new case</button></form></Panel>
    <Panel title="Run the selected case" caption="CLEAN BASELINE + FAULTED EXECUTION"><form className="form" onSubmit={e => { e.preventDefault(); void submit({ kind: "campaign", caseId: selected, variant, maxSeconds: 360 }); }}><p className="muted">Runs use the immutable scenario already saved in this case. Saving a new configuration creates a new case.</p>{current && <dl className="facts"><dt>Scenario</dt><dd>{scenarioName(current)}</dd><dt>Inputs / events</dt><dd>{current.provenance.inputs} / {current.provenance.events}</dd><dt>Capture</dt><dd className="mono">{short(current.provenance.capture?.captureId)}</dd><dt>Coverage</dt><dd>{current.provenance.coverage?.status}</dd></dl>}<label>Consumer variant<select value={variant} onChange={e => setVariant(e.target.value)}><option value="faulty">Faulty · intentional sample defect</option><option value="fixed">Fixed · atomic effects & checkpoint</option></select></label><button className="primary" disabled={busy || !selected}>Run campaign <Icon name="campaigns" /></button></form></Panel></div>
    <Panel title="Scenario × consumer" caption="ACTUAL SAVED CAMPAIGN OUTCOMES"><div className="table-wrap"><table><thead><tr><th>Case / scenario</th><th>Faulty sample</th><th>Fixed sample</th></tr></thead><tbody>{cases.map(c => <tr key={c.id}><td><span className="mono">{short(c.id)}</span><br /><span className="muted">{scenarioName(c)}</span></td>{["faulty", "fixed"].map(v => { const r = runs.find(r => r.caseId === c.id && r.variant === v && (r.kind ?? "campaign") === "campaign"), comparison = runs.find(r => r.caseId === c.id && r.kind === "compare" && r.result?.comparison), pair = comparison?.result.comparison.cases[0]; return <td key={v}>{comparison && pair ? <button className="status-link" onClick={() => go(`run/${comparison.id}`)}><Status value={v === "faulty" ? pair.faultyConfirmed === pair.repeats ? "FAIL" : "INCONCLUSIVE" : pair.fixedPassed === pair.repeats ? "PASS" : pair.verdict} /><span className="muted">{v === "faulty" ? pair.faultyConfirmed : pair.fixedPassed}/{pair.repeats} {v === "faulty" ? "reproduced" : "passed"}</span></button> : r ? <button className="status-link" onClick={() => go(`run/${r.id}`)}><Status value={r.verdict ?? r.state} /></button> : <span className="muted">Not run</span>}</td>; })}</tr>)}</tbody></table></div></Panel>
    <Panel title="Campaign history"><RunsTable runs={runs.filter(r => (r.kind ?? "campaign") === "campaign")} go={go} /></Panel></>;
}
export function Cases({ cases, runs, go }: { cases: Case[]; runs: Run[] } & Pick<Actions, "go">) {
  const [search, setSearch] = useState("");
  const filtered = cases.filter(c => `${c.id} ${c.provenance.capture?.captureId ?? ""} ${scenarioName(c)} ${c.provenance.sourceMode}`.toLowerCase().includes(search.toLowerCase()));
  return <><Header eyebrow="04 / KEEP" title="A case you can take with you." description="Original inputs, reduced failures and verified histories stay linked to their source." /><Panel title="Case library" caption={`${cases.length} immutable cases`} action={<label className="search"><span className="sr-only">Search cases</span><input placeholder="Search cases or capture ID…" value={search} onChange={e => setSearch(e.target.value)} /></label>}>
    {filtered.length ? <div className="table-wrap"><table><thead><tr><th>Case</th><th>Source capture</th><th>Inputs / events</th><th>Scenario</th><th>Source</th></tr></thead><tbody>{filtered.map(c => <tr key={c.id}><td><button className="text-button mono" onClick={() => go(`case/${c.id}`)}>{short(c.id)} ↗</button></td><td className="mono">{short(c.provenance.capture?.captureId)}</td><td>{c.provenance.inputs} / {c.provenance.events}</td><td>{scenarioName(c)}</td><td><span className="label">{c.provenance.sourceMode}</span></td></tr>)}</tbody></table></div> : <Empty title="No matching cases" text="Prepare a recording or adjust the search to find a saved case." />}</Panel><Panel title="Reduction, comparison & exports"><RunsTable runs={runs.filter(r => ["reduce", "compare", "export"].includes(r.kind))} go={go} /></Panel></>;
}
export function Runner({ capabilities, mode }: { capabilities: any; mode: string }) {
  return <><Header eyebrow="EXECUTION BOUNDARY" title="Know what this runner can prove." description="Capabilities are checked before work begins. Private consumer code stays on your machine." /><div className="two-col"><Panel title="Connected runner" caption={mode === "local" ? "THIS MACHINE · LOCAL EXECUTION" : "HOSTED MAINTAINED SAMPLES"}><dl className="facts"><dt>Adapter</dt><dd>{capabilities?.adapter}</dd><dt>Variants</dt><dd>Maintained faulty / fixed</dd><dt>State isolation</dt><dd>Fresh owned PostgreSQL per run</dd><dt>Worker ownership</dt><dd>Leases + fenced generations</dd><dt>Private code upload</dt><dd>Unavailable</dd></dl><div className="note">To work locally, run <code>pnpm api</code> and <code>pnpm worker</code> in your checkout. Open the local workbench below; its recordings and execution stay on that machine.</div><a className="button" href="http://127.0.0.1:8787" target="_blank" rel="noreferrer">Open connected local runner ↗</a><p className="muted">The full external consumer adapter is a later phase. This workbench currently executes the maintained trade sample.</p></Panel><Panel title="Capability checks"><div className="capability-list">{[["State reset & inspection", "SUPPORTED"], ["Real crash after durable commit", "SUPPORTED"], ["Duplicate and reconnect overlap", "SUPPORTED"], ["Recovery of one held input", "SUPPORTED"], ["Arbitrary mid-statement crash", "UNSUPPORTED"], ["Private external consumer execution", "UNSUPPORTED"]].map(([label, value]) => <div key={label}><span>{label}</span><Status value={value!} /></div>)}</div></Panel></div><Panel title="Resource limits & qualified claims"><JsonView value={capabilities?.limits} /><ul className="plain-list">{capabilities?.limitations?.map((text: string) => <li key={text}>{text}</li>)}</ul></Panel></>;
}
