import { useEffect, useState, type FormEvent } from "react";
import { api, bytes, presets, scenarioName, short, stamp, type Capture, type Case, type Project, type Run } from "./model";
import { latestCaseOutcome, relatedCaseRuns, sourceName } from "./workflow";
import { Empty, Header, Icon, JsonView, Panel, RunsTable, Status } from "./ui";
export type Actions = { go: (route: string) => void; submit: (settings: Record<string, unknown>) => Promise<void>; busy: boolean };
export function Overview({ project, cases, captures, runs, go }: { project: Project; cases: Case[]; captures: Capture[]; runs: Run[] } & Pick<Actions, "go">) {
  const campaigns = runs.filter(r => r.kind === "campaign"), failures = campaigns.filter(r => r.verdict === "FAIL"), failure = failures[0], active = runs.filter(r => ["QUEUED", "RUNNING"].includes(r.state));
  const stats = [{ title: "Captures", value: captures.length, detail: "Saved recordings", icon: "captures", route: "captures" }, { title: "Campaigns", value: campaigns.length, detail: `${active.length} in progress`, icon: "campaigns", route: "campaigns" }, { title: "Incidents", value: failures.length, detail: "Failed assertions", icon: "incidents", route: "incidents" }, { title: "Cases", value: cases.length, detail: "Saved for replay", icon: "cases", route: "cases" }];
  const chain = relatedCaseRuns(runs, failure?.result?.caseId ?? failure?.caseId), reduction = chain.find(r => r.kind === "reduce" && r.verdict === "PASS"), fix = chain.find(r => r.kind === "compare" && r.verdict === "PASS"), exported = chain.find(r => r.kind === "export" && r.verdict === "PASS");
  const pair = fix?.result?.comparison?.cases[0];
  const captureId = failure?.result?.provenance?.capture?.captureId, recording = captures.find(c => c.summary.captureId === captureId);
  const steps = [{ label: "Recording", detail: recording ? `${recording.summary.transactions} transactions` : failure?.result?.provenance?.sourceMode === "synthetic" ? "Synthetic inputs" : "Source case", route: recording ? `capture/${captureId}` : `case/${failure?.caseId}`, ready: !!recording || failure?.result?.provenance?.sourceMode === "synthetic", icon: "captures" }, { label: "Campaign", detail: "Assertion failed", route: `run/${failure?.id}`, ready: true, icon: "campaigns" }, { label: "Reduction", detail: reduction ? `${reduction.result.reduction.retainedInputs.length} input${reduction.result.reduction.retainedInputs.length === 1 ? "" : "s"} retained` : "Not reduced", route: reduction ? `run/${reduction.id}` : `case/${failure?.result?.caseId ?? failure?.caseId}`, ready: !!reduction, icon: "cases" }, { label: "Fix check", detail: fix ? "Comparison passed" : "Not compared", route: fix ? `run/${fix.id}` : `case/${failure?.result?.caseId ?? failure?.caseId}`, ready: !!fix, icon: "verified" }, { label: "Offline test", detail: exported ? "Bundle ready" : "Not exported", route: exported ? `run/${exported.id}` : `case/${failure?.result?.caseId ?? failure?.caseId}`, ready: !!exported, icon: "download" }];
  return <><Header title="Overview" description={`${project.name} · Trade ledger`}><button onClick={() => go("campaigns")}><Icon name="campaigns" />Run campaign</button><button className="primary" onClick={() => go("captures")}><Icon name="plus" />New capture</button></Header>
    <div className="metric-grid">{stats.map(s => <button className={`metric ${s.icon}`} key={s.title} onClick={() => go(s.route)}><span className="metric-label"><Icon name={s.icon} />{s.title}<Icon name="external" /></span><strong>{s.value}</strong><span className="metric-detail">{s.detail}</span></button>)}</div>
    <div className="overview-evidence">{failure ? <section className="investigation"><div className="investigation-head"><div className="investigation-symbol"><Icon name="crash" /></div><div><span className="eyebrow">Latest incident</span><h2>{failure.result?.provenance?.scenario?.faults?.some((f: any) => f.kind === "crash") ? "Crash after commit" : "State assertion failed"}</h2></div><Status value="FAIL" /><button onClick={() => go(`run/${failure.id}`)}>Inspect failure <Icon name="arrow" /></button></div><div className="investigation-meta"><span className="mono">{short(failure.id)}</span><span>{failure.result?.discrepancies?.length ?? 0} fields differ</span><span>{sourceName(failure.result?.provenance?.sourceMode)}</span><span>{stamp(failure.createdAtUtc)}</span></div><div className="investigation-path" aria-label="Saved evidence for the latest incident">{steps.map((s, i) => <button key={s.label} className={s.ready ? "ready" : "waiting"} onClick={() => go(s.route)}><span className="path-node"><Icon name={s.icon} /></span><span><strong>{s.label}</strong><small>{s.detail}</small></span>{i < steps.length - 1 && <span className="path-connector" aria-hidden="true" />}</button>)}</div></section> : <section className="getting-started"><div><Icon name="captures" /><h2>Start with a recording</h2><p>Capture inputs, prepare a case, then test its recovery.</p></div><button className="primary" onClick={() => go("captures")}>New capture <Icon name="arrow" /></button></section>}
    <aside className="overview-proof" aria-label="Fix comparison"><h2>Fix comparison</h2>{pair ? <><div className="proof-result"><Icon name="verified" /><strong>{pair.fixedPassed}/{pair.repeats}</strong><Status value={fix!.verdict} /></div><p>Fixed variant · fresh state each run</p><dl><dt>Faulty reproduced</dt><dd>{pair.faultyConfirmed}/{pair.repeats}</dd><dt>Compared</dt><dd>{stamp(fix!.createdAtUtc)}</dd></dl><button className="text-button" onClick={() => go(`run/${fix!.id}`)}>Open comparison <Icon name="arrow" /></button></> : <><p>No comparison saved for this incident.</p><button className="text-button" onClick={() => go("cases")}>Choose a case <Icon name="arrow" /></button></>}</aside></div>
    <Panel title="Recent activity"><RunsTable searchable runs={runs} go={go} /></Panel>
  </>;
}
export function Captures({ captures, runs, submit, go, busy, initialCapture }: { captures: Capture[]; runs: Run[]; initialCapture?: string } & Actions) {
  const [duration, setDuration] = useState(10), [transactions, setTransactions] = useState(25), [commitment, setCommitment] = useState("confirmed"), [selected, setSelected] = useState<string | null>(null), [exclude, setExclude] = useState(false);
  useEffect(() => { setSelected(initialCapture ? captures.find(c => c.summary.captureId === initialCapture)?.id ?? null : null); }, [initialCapture, captures]);
  const current = captures.find(c => c.id === selected);
  const launch = (e: FormEvent) => { e.preventDefault(); void submit({ kind: "capture", durationSeconds: duration, maxTransactions: transactions, maxBytes: 2097152, commitment, maxSeconds: 120 }); };
  return <>{current && <button className="back-link text-button" onClick={() => go("captures")}><Icon name="back" />Captures</button>}<Header title={current ? `Recording ${short(current.summary.captureId)}` : "Captures"} description={current ? "Sealed inputs and finalized reference." : "Record mainnet inputs for replay. Check finalization separately."} />
    {!current && <div className="two-col"><Panel title="New live capture" caption="SOLAMI · YELLOWSTONE · SOLANA MAINNET"><form onSubmit={launch} className="form"><div className="source-line"><span className="source-dot" /> Pump.fun account mention filter</div><p className="muted">Successful, non-vote transactions mentioning the program. An account mention does not prove invocation or a swap.</p><div className="form-row"><label>Duration (seconds)<input type="number" min="1" max="30" value={duration} onChange={e => setDuration(+e.target.value)} required /></label><label>Transaction cap<input type="number" min="1" max="100" value={transactions} onChange={e => setTransactions(+e.target.value)} required /></label></div><label>Commitment<select value={commitment} onChange={e => setCommitment(e.target.value)}><option value="confirmed">Confirmed</option><option value="finalized">Finalized</option></select></label><div className="note">Stops at the first limit: time, transactions, 200 frames or 2 MB.</div><button className="primary" disabled={busy}>Start live capture <Icon name="captures" /></button></form></Panel>
      <Panel title="Prepare a recording" caption="Three steps"><ol className="explain-list"><li><strong>Record & seal</strong><p>Save raw messages with timestamps and checksums.</p></li><li><strong>Check finalized membership</strong><p>Check which transactions appear in finalized blocks. This does not prove capture completeness.</p></li><li><strong>Decode supported trades</strong><p>Prepare inputs with the pinned decoder. Unsupported v1 inputs require explicit exclusion.</p></li></ol></Panel></div>}
    {current && <Panel title="Recording details" caption="SEALED RAW EVIDENCE" action={<button className="text-button" onClick={() => { setSelected(null); go("captures"); }}>Close <Icon name="close" /></button>}><div className="two-col inset"><div><dl className="facts"><dt>Stopped</dt><dd>{current.summary.stopReason.replaceAll("-", " ")}</dd><dt>Manifest SHA-256</dt><dd className="mono hash">{current.manifestSha256}</dd><dt>Last received</dt><dd>{current.summary.frames?.at(-1)?.receivedAtUtc ?? "See frame manifest"}</dd><dt>Completeness</dt><dd>Not established</dd></dl><button disabled={busy} onClick={() => void submit({ kind: "reference", captureId: current.id, maxSeconds: 180 })}>Check finalized reference</button>{current.reference && <details><summary>Inspect finalized reference</summary><JsonView value={current.reference} /></details>}</div><form className="form" onSubmit={e => { e.preventDefault(); void submit({ kind: "normalize", captureId: current.id, allowV1Exclusions: exclude, preset: "crash", seed: "workbench", maxSeconds: 180 }); }}><h3>Prepare a trade case</h3><p className="muted">Keeps the capture, signatures, hashes and exclusions with the case.</p><label className="check"><input type="checkbox" checked={exclude} onChange={e => setExclude(e.target.checked)} /> Explicitly exclude unsupported v1 inputs</label><button className="primary" disabled={busy}>Decode & prepare case <Icon name="arrow" /></button></form></div><details><summary>Inspect capture manifest</summary><JsonView value={current.summary} /></details></Panel>}
    <Panel title="Recordings on this runner" caption={`${captures.length} recordings`}>
      {!captures.length ? <Empty title="No registered recordings" text="Start a bounded live capture, or import an existing recording with the local CLI." /> : <div className="table-wrap"><table><thead><tr><th>Capture</th><th>Source</th><th>Recorded</th><th>Transactions</th><th>Size</th><th>Reference</th></tr></thead><tbody>{captures.map(c => <tr key={c.id}><td><button className="text-button mono" onClick={() => go(`capture/${c.summary.captureId}`)}>{short(c.summary.captureId)} <Icon name="external" /></button></td><td><span className="label">{c.summary.sourceMode === "live-mainnet" ? "LIVE RECORDING" : "SAVED MAINNET"}</span></td><td>{stamp(c.summary.startedAtUtc)}</td><td>{c.summary.transactions}</td><td>{bytes(c.summary.rawBytes)}</td><td><Status value={c.reference?.result?.verdict ?? "NOT ASSESSED"} /></td></tr>)}</tbody></table></div>}
    </Panel>
    <Panel title="Capture operations"><RunsTable searchable runs={runs.filter(r => ["capture", "normalize", "reference"].includes(r.kind))} go={go} /></Panel></>;
}
export function Campaigns({ cases, runs, submit, go, busy, initialCase }: { cases: Case[]; runs: Run[]; initialCase?: string } & Actions) {
  const [selected, setSelected] = useState(cases.find(c => c.id === initialCase)?.id ?? cases[0]?.id ?? ""), [preset, setPreset] = useState("crash"), [seed, setSeed] = useState("workbench"), [variant, setVariant] = useState("faulty"), [configure, setConfigure] = useState(false);
  const current = cases.find(c => c.id === selected), choice = presets.find(p => p.id === preset)!;
  return <><Header title="Campaigns" description="Replay a saved case against an isolated consumer." />
    {!cases.length ? <Panel title="Start a campaign"><Empty title="A saved case is required" text="Capture and prepare inputs before running a campaign."><button className="primary" onClick={() => go("captures")}><Icon name="plus" />New capture</button></Empty></Panel> : <div className="campaign-layout"><Panel title="Campaign setup" action={<span className="subtle-tag">Trade ledger</span>}><form className="form" onSubmit={e => { e.preventDefault(); void submit(configure ? { kind: "scenario", caseId: selected, preset, seed } : { kind: "campaign", caseId: selected, variant, maxSeconds: 360 }); }}>
      <label>Source case<select value={selected} onChange={e => setSelected(e.target.value)} required><option value="" disabled>Select a case</option>{cases.map(c => <option key={c.id} value={c.id}>{short(c.id)} · {c.provenance.inputs} inputs · {sourceName(c.provenance.sourceMode)}</option>)}</select></label>
      <fieldset className="segmented"><legend className="sr-only">Scenario mode</legend><label className={!configure ? "selected" : ""}><input type="radio" name="scenario-mode" checked={!configure} onChange={() => setConfigure(false)} />Run saved scenario</label><label className={configure ? "selected" : ""}><input type="radio" name="scenario-mode" checked={configure} onChange={() => setConfigure(true)} />Create a scenario</label></fieldset>
      {configure ? <><fieldset className="preset-options"><legend>Fault preset</legend>{presets.map(p => <label key={p.id} className={`preset-option ${preset === p.id ? "selected" : ""}`}><input type="radio" name="preset" value={p.id} checked={preset === p.id} onChange={() => setPreset(p.id)} /><Icon name={p.id === "crash" ? "crash" : p.id === "duplicate" ? "copy" : p.id === "disconnect" ? "disconnected" : "cases"} /><span><strong>{p.name}</strong><small>{p.text}</small></span><span className="radio-indicator" /></label>)}</fieldset><label>Seed<input maxLength={80} value={seed} onChange={e => setSeed(e.target.value)} required /></label><p className="field-hint">Saves a new case. The original case is unchanged.</p></> : <><div className="saved-scenario"><Icon name="crash" /><div><span>Saved scenario</span><strong>{current ? scenarioName(current) : "Select a case"}</strong></div><span className="subtle-tag">Locked</span></div><fieldset className="variant-options"><legend>Consumer variant</legend>{["faulty", "fixed"].map(v => <label key={v} className={variant === v ? "selected" : ""}><input type="radio" name="variant" checked={variant === v} onChange={() => setVariant(v)} /><Icon name={v === "fixed" ? "verified" : "incidents"} /><strong>{v === "fixed" ? "Fixed" : "Faulty"}</strong><span>{v === "fixed" ? "Atomic effects & checkpoint" : "Intentional sample defect"}</span></label>)}</fieldset></>}
      <div className="form-submit"><span><Icon name="clock" />{configure ? "Saved as a separate case" : "6 minute limit · Fresh database"}</span><button className="primary" disabled={busy || !selected}><Icon name={configure ? "plus" : "campaigns"} />{busy ? "Submitting…" : configure ? "Save scenario" : "Run campaign"}</button></div>
    </form></Panel><div className="campaign-aside"><Panel title="Selected inputs" action={<Icon name="source" />}>{current && <><dl className="facts"><dt>Case</dt><dd><button className="text-button mono" onClick={() => go(`case/${current.id}`)}>{short(current.id)}<Icon name="external" /></button></dd><dt>Inputs / events</dt><dd className="mono">{current.provenance.inputs} / {current.provenance.events}</dd><dt>Source</dt><dd>{sourceName(current.provenance.sourceMode)}</dd><dt>Capture</dt><dd className="mono">{short(current.provenance.capture?.captureId)}</dd><dt>Coverage</dt><dd>{current.provenance.coverage?.status}</dd></dl><div className="note">{configure ? choice.expectation : "Checks the clean baseline, then applies this case’s saved fault."}</div></>}</Panel><div className="execution-steps"><span className="eyebrow">Execution order</span><div><span>01</span><p>Reset disposable state</p></div><div><span>02</span><p>Check clean baseline</p></div><div><span>03</span><p>Apply fault & recover</p></div><div><span>04</span><p>Compare saved state</p></div></div></div></div>}
    <Panel title="Scenario × consumer" caption="Saved campaign outcomes"><div className="table-wrap"><table><thead><tr><th>Case / scenario</th><th>Faulty sample</th><th>Fixed sample</th></tr></thead><tbody>{cases.map(c => <tr key={c.id}><td><span className="mono">{short(c.id)}</span><br /><span className="muted">{scenarioName(c)}</span></td>{["faulty", "fixed"].map(v => { const outcome = latestCaseOutcome(runs, c.id, v); return <td key={v}>{outcome ? <button className="status-link" onClick={() => go(`run/${outcome.run.id}`)}><Status value={outcome.verdict} />{outcome.detail && <span className="muted">{outcome.detail}</span>}</button> : <span className="muted">Not run</span>}</td>; })}</tr>)}</tbody></table></div></Panel>
    <Panel title="Campaign history"><RunsTable searchable runs={runs.filter(r => (r.kind ?? "campaign") === "campaign")} go={go} /></Panel></>;
}
export function Cases({ cases, runs, go }: { cases: Case[]; runs: Run[] } & Pick<Actions, "go">) {
  const [search, setSearch] = useState(""), [sourceFilter, setSourceFilter] = useState("all");
  const filtered = cases.filter(c => `${c.id} ${c.provenance.capture?.captureId ?? ""} ${scenarioName(c)} ${c.provenance.sourceMode}`.toLowerCase().includes(search.toLowerCase()) && (sourceFilter === "all" || (sourceFilter === "synthetic" ? c.provenance.sourceMode.includes("synthetic") : !c.provenance.sourceMode.includes("synthetic"))));
  return <><Header title="Case library" description="Saved inputs, reduced failures, and offline tests." /><Panel title="Case library" caption={`${cases.length} immutable cases`} action={<span className="subtle-tag">Immutable</span>}>
    <div className="table-tools"><label className="search"><Icon name="search" /><span className="sr-only">Search cases</span><input placeholder="Search cases or capture ID…" value={search} onChange={e => setSearch(e.target.value)} /></label><label className="filter-select"><Icon name="filter" /><span className="sr-only">Filter source</span><select value={sourceFilter} onChange={e => setSourceFilter(e.target.value)}><option value="all">All sources</option><option value="mainnet">Mainnet recordings</option><option value="synthetic">Synthetic fixtures</option></select></label></div>
    {filtered.length ? <div className="table-wrap"><table><thead><tr><th>Case</th><th>Source capture</th><th>Inputs / events</th><th>Scenario</th><th>Source</th></tr></thead><tbody>{filtered.map(c => <tr key={c.id}><td><button className="text-button mono" onClick={() => go(`case/${c.id}`)}>{short(c.id)} <Icon name="external" /></button></td><td className="mono">{short(c.provenance.capture?.captureId)}</td><td>{c.provenance.inputs} / {c.provenance.events}</td><td>{scenarioName(c)}</td><td><span className="label">{sourceName(c.provenance.sourceMode)}</span></td></tr>)}</tbody></table></div> : <Empty title="No matching cases" text="Prepare a recording or adjust the search to find a saved case." />}</Panel><Panel title="Reduction, comparison & exports"><RunsTable searchable runs={runs.filter(r => ["reduce", "compare", "export"].includes(r.kind))} go={go} /></Panel></>;
}
export function Runner({ capabilities, mode }: { capabilities: any; mode: string }) {
  return <><Header title="Runner settings" description="Execution support and resource limits." /><div className="two-col"><Panel title="Connected runner" caption={mode === "local" ? "THIS MACHINE · LOCAL EXECUTION" : "HOSTED MAINTAINED SAMPLES"}><dl className="facts"><dt>Adapter</dt><dd>{capabilities?.adapter}</dd><dt>Variants</dt><dd>Maintained faulty / fixed</dd><dt>State isolation</dt><dd>Fresh owned PostgreSQL per run</dd><dt>Worker ownership</dt><dd>Leases + fenced generations</dd><dt>Private code upload</dt><dd>Unavailable</dd></dl><div className="note">To work locally, run <code>pnpm api</code> and <code>pnpm worker</code> in your checkout. Open the local workbench below; its recordings and execution stay on that machine.</div><a className="button" href="http://127.0.0.1:8787" target="_blank" rel="noreferrer">Open connected local runner <Icon name="external" /></a><p className="muted">The full external consumer adapter is a later phase. This workbench currently executes the maintained trade sample.</p></Panel><Panel title="Capability checks"><div className="capability-list">{[["State reset & inspection", "SUPPORTED"], ["Real crash after durable commit", "SUPPORTED"], ["Duplicate and reconnect overlap", "SUPPORTED"], ["Recovery of one held input", "SUPPORTED"], ["Arbitrary mid-statement crash", "UNSUPPORTED"], ["Private external consumer execution", "UNSUPPORTED"]].map(([label, value]) => <div key={label}><span>{label}</span><Status value={value!} /></div>)}</div></Panel></div><Panel title="Resource limits"><JsonView value={capabilities?.limits} /><ul className="plain-list">{capabilities?.limitations?.map((text: string) => <li key={text}>{text}</li>)}</ul></Panel></>;
}
